-- Migration 021 — Carga de las reglas de lista (26/08/2026). Idempotente.
--
-- GENERADO por scripts/gen-listas-seed.mjs desde la planilla "CONDICIONES LISTA SEMILLERO"
-- de Mati + scripts/listas-mapeo.json. NO editar a mano: corregir el mapeo y volver a generar.
--
-- Las reglas con activo=false son las que todavía no confirmó cuál es su equivalente en
-- InfoManager. Quedan cargadas para no perder el trabajo, pero el validador no las evalúa.

insert into listas_reglas (nombre, match_tipo, match_valor, cod_lista, condicion, umbral, unidad, ambito, activo, nota) values
  ('LINEA GANAVE', 'subrubro', 'Ganave', 12, 'libre', null, null, null, true, null),
  ('LINEA GANAVE', 'subrubro', 'Ganave', 13, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('CONEJO GEPSA', 'subrubro', 'Gepsa', 12, 'libre', null, null, null, true, null),
  ('CONEJO GEPSA', 'subrubro', 'Gepsa', 13, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('CONEJO GEPSA', 'subrubro', 'Gepsa', 14, 'min', 10, 'bulto', 'articulo', true, null),
  ('CONEJO GEPSA', 'subrubro', 'Gepsa', 15, 'min', 30, 'bulto', 'articulo', true, null),
  ('CONEJO COENCAR', 'subrubro', 'Conecar', 12, 'libre', null, null, null, true, 'La planilla dice COENCAR, en IM el subrubro es "Conecar" (arts 6 y 25, que se llaman CONECAR). Mismo producto.'),
  ('CONEJO COENCAR', 'subrubro', 'Conecar', 13, 'promo_general', 10, 'bulto', 'pedido', true, 'La planilla dice COENCAR, en IM el subrubro es "Conecar" (arts 6 y 25, que se llaman CONECAR). Mismo producto.'),
  ('CONEJO COENCAR', 'subrubro', 'Conecar', 14, 'min', 10, 'bulto', 'articulo', true, 'La planilla dice COENCAR, en IM el subrubro es "Conecar" (arts 6 y 25, que se llaman CONECAR). Mismo producto.'),
  ('CONEJO COENCAR', 'subrubro', 'Conecar', 15, 'min', 30, 'bulto', 'articulo', true, 'La planilla dice COENCAR, en IM el subrubro es "Conecar" (arts 6 y 25, que se llaman CONECAR). Mismo producto.'),
  ('LINEA PRODUCCION PROPIA SEMILLERO', 'subrubro', 'Semillero', 12, 'libre', null, null, null, true, null),
  ('LINEA PRODUCCION PROPIA SEMILLERO', 'subrubro', 'Semillero', 13, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('LINEA PRODUCCION PROPIA SEMILLERO', 'subrubro', 'Semillero', 14, 'min', 30, 'bulto', 'linea', true, null),
  ('LINEA PRODUCCION PROPIA SEMILLERO', 'subrubro', 'Semillero', 15, 'min', 50, 'bulto', 'articulo', true, null),
  ('LINEA ROSCO', 'subrubro', 'Rosco', 12, 'libre', null, null, null, true, null),
  ('LINEA ROSCO', 'subrubro', 'Rosco', 13, 'libre', null, null, null, true, null),
  ('LINEA ROSCO', 'subrubro', 'Rosco', 14, 'libre', null, null, null, true, null),
  ('LINEA TIERNITO', 'subrubro', 'Tiernitos', 12, 'libre', null, null, null, true, 'El alimento en bolsa: subrubros "Tiernitos" (perro, 15/21 kg) y "Tiernito" (gato, 10 kg). Los SNACK TIERNITO viven en el mismo subrubro pero tienen regla propia por codigo, y la regla por articulo le gana a la del subrubro.'),
  ('LINEA TIERNITO', 'subrubro', 'Tiernitos', 13, 'promo_general', 10, 'bulto', 'pedido', true, 'El alimento en bolsa: subrubros "Tiernitos" (perro, 15/21 kg) y "Tiernito" (gato, 10 kg). Los SNACK TIERNITO viven en el mismo subrubro pero tienen regla propia por codigo, y la regla por articulo le gana a la del subrubro.'),
  ('LINEA TIERNITO', 'subrubro', 'Tiernitos', 14, 'min', 5, 'bulto', 'linea', true, 'El alimento en bolsa: subrubros "Tiernitos" (perro, 15/21 kg) y "Tiernito" (gato, 10 kg). Los SNACK TIERNITO viven en el mismo subrubro pero tienen regla propia por codigo, y la regla por articulo le gana a la del subrubro.'),
  ('LINEA TIERNITO', 'subrubro', 'Tiernito', 12, 'libre', null, null, null, true, 'El alimento en bolsa: subrubros "Tiernitos" (perro, 15/21 kg) y "Tiernito" (gato, 10 kg). Los SNACK TIERNITO viven en el mismo subrubro pero tienen regla propia por codigo, y la regla por articulo le gana a la del subrubro.'),
  ('LINEA TIERNITO', 'subrubro', 'Tiernito', 13, 'promo_general', 10, 'bulto', 'pedido', true, 'El alimento en bolsa: subrubros "Tiernitos" (perro, 15/21 kg) y "Tiernito" (gato, 10 kg). Los SNACK TIERNITO viven en el mismo subrubro pero tienen regla propia por codigo, y la regla por articulo le gana a la del subrubro.'),
  ('LINEA TIERNITO', 'subrubro', 'Tiernito', 14, 'min', 5, 'bulto', 'linea', true, 'El alimento en bolsa: subrubros "Tiernitos" (perro, 15/21 kg) y "Tiernito" (gato, 10 kg). Los SNACK TIERNITO viven en el mismo subrubro pero tienen regla propia por codigo, y la regla por articulo le gana a la del subrubro.'),
  ('LINEA DS CRIADORES', 'subrubro', 'Dog Seleccion', 12, 'libre', null, null, null, true, 'El subrubro en IM se llama "Dog Seleccion" pero los 10 articulos se llaman DS CRIADORES / DS ETIQ. Es la misma linea.'),
  ('LINEA DS CRIADORES', 'subrubro', 'Dog Seleccion', 13, 'libre', null, null, null, true, 'El subrubro en IM se llama "Dog Seleccion" pero los 10 articulos se llaman DS CRIADORES / DS ETIQ. Es la misma linea.'),
  ('LINEA DS CRIADORES', 'subrubro', 'Dog Seleccion', 14, 'libre', null, null, null, true, 'El subrubro en IM se llama "Dog Seleccion" pero los 10 articulos se llaman DS CRIADORES / DS ETIQ. Es la misma linea.'),
  ('LINEA GRAN CAMPEON', 'subrubro', 'Gran Campeon', 12, 'libre', null, null, null, true, 'Mati 26/08: llega hasta LISTA 3. El audio decia L4 pero estaba mal (quiso decir el mejor precio).'),
  ('LINEA GRAN CAMPEON', 'subrubro', 'Gran Campeon', 13, 'libre', null, null, null, true, 'Mati 26/08: llega hasta LISTA 3. El audio decia L4 pero estaba mal (quiso decir el mejor precio).'),
  ('LINEA GRAN CAMPEON', 'subrubro', 'Gran Campeon', 14, 'libre', null, null, null, true, 'Mati 26/08: llega hasta LISTA 3. El audio decia L4 pero estaba mal (quiso decir el mejor precio).'),
  ('LINEA PACHA', 'subrubro', 'Pacha', 12, 'libre', null, null, null, true, null),
  ('LINEA PACHA', 'subrubro', 'Pacha', 13, 'libre', null, null, null, true, null),
  ('LINEA BELCAN', 'subrubro', 'Belcan', 12, 'libre', null, null, null, false, 'Existe el subrubro "Belcat" (3 arts: BELCAT X 10KG y un pouch). Belcan es perro y Belcat gato: van con la misma regla?'),
  ('LINEA BELCAN', 'subrubro', 'Belcan', 13, 'libre', null, null, null, false, 'Existe el subrubro "Belcat" (3 arts: BELCAT X 10KG y un pouch). Belcan es perro y Belcat gato: van con la misma regla?'),
  ('LINEA BELCAN', 'subrubro', 'Belcan', 14, 'libre', null, null, null, false, 'Existe el subrubro "Belcat" (3 arts: BELCAT X 10KG y un pouch). Belcan es perro y Belcat gato: van con la misma regla?'),
  ('LINEA BELCAN', 'subrubro', 'Belcan', 15, 'libre', null, null, null, false, 'Existe el subrubro "Belcat" (3 arts: BELCAT X 10KG y un pouch). Belcan es perro y Belcat gato: van con la misma regla?'),
  ('LINEA BELCAN', 'subrubro', 'Belcat', 12, 'libre', null, null, null, false, 'Existe el subrubro "Belcat" (3 arts: BELCAT X 10KG y un pouch). Belcan es perro y Belcat gato: van con la misma regla?'),
  ('LINEA BELCAN', 'subrubro', 'Belcat', 13, 'libre', null, null, null, false, 'Existe el subrubro "Belcat" (3 arts: BELCAT X 10KG y un pouch). Belcan es perro y Belcat gato: van con la misma regla?'),
  ('LINEA BELCAN', 'subrubro', 'Belcat', 14, 'libre', null, null, null, false, 'Existe el subrubro "Belcat" (3 arts: BELCAT X 10KG y un pouch). Belcan es perro y Belcat gato: van con la misma regla?'),
  ('LINEA BELCAN', 'subrubro', 'Belcat', 15, 'libre', null, null, null, false, 'Existe el subrubro "Belcat" (3 arts: BELCAT X 10KG y un pouch). Belcan es perro y Belcat gato: van con la misma regla?'),
  ('LINEA ZIMPI', 'subrubro', 'Zimpi', 12, 'libre', null, null, null, true, 'La linea esta partida en IM por un typo: subrubros "Zimpy" (3) y "Zimpi" (1), todos articulos ZIMPI. Se toman los dos.'),
  ('LINEA ZIMPI', 'subrubro', 'Zimpi', 13, 'promo_general', 10, 'bulto', 'pedido', true, 'La linea esta partida en IM por un typo: subrubros "Zimpy" (3) y "Zimpi" (1), todos articulos ZIMPI. Se toman los dos.'),
  ('LINEA ZIMPI', 'subrubro', 'Zimpi', 14, 'min', 5, 'bulto', 'linea', true, 'La linea esta partida en IM por un typo: subrubros "Zimpy" (3) y "Zimpi" (1), todos articulos ZIMPI. Se toman los dos.'),
  ('LINEA ZIMPI', 'subrubro', 'Zimpi', 15, 'min', 20, 'bulto', 'linea', true, 'La linea esta partida en IM por un typo: subrubros "Zimpy" (3) y "Zimpi" (1), todos articulos ZIMPI. Se toman los dos.'),
  ('LINEA ZIMPI', 'subrubro', 'Zimpy', 12, 'libre', null, null, null, true, 'La linea esta partida en IM por un typo: subrubros "Zimpy" (3) y "Zimpi" (1), todos articulos ZIMPI. Se toman los dos.'),
  ('LINEA ZIMPI', 'subrubro', 'Zimpy', 13, 'promo_general', 10, 'bulto', 'pedido', true, 'La linea esta partida en IM por un typo: subrubros "Zimpy" (3) y "Zimpi" (1), todos articulos ZIMPI. Se toman los dos.'),
  ('LINEA ZIMPI', 'subrubro', 'Zimpy', 14, 'min', 5, 'bulto', 'linea', true, 'La linea esta partida en IM por un typo: subrubros "Zimpy" (3) y "Zimpi" (1), todos articulos ZIMPI. Se toman los dos.'),
  ('LINEA ZIMPI', 'subrubro', 'Zimpy', 15, 'min', 20, 'bulto', 'linea', true, 'La linea esta partida en IM por un typo: subrubros "Zimpy" (3) y "Zimpi" (1), todos articulos ZIMPI. Se toman los dos.'),
  ('ARROZ P PARRO', 'subrubro', 'Arroz p/perro', 12, 'libre', null, null, null, true, 'Es ARROZ P/ PERRO: subrubro "Arroz p/perro", art 160 ARROZ PARA PERRO LUMPY.'),
  ('ARROZ P PARRO', 'subrubro', 'Arroz p/perro', 13, 'promo_general', 10, 'bulto', 'pedido', true, 'Es ARROZ P/ PERRO: subrubro "Arroz p/perro", art 160 ARROZ PARA PERRO LUMPY.'),
  ('COMPINCHE', 'subrubro', 'Compinche', 12, 'libre', null, null, null, true, null),
  ('COMPINCHE', 'subrubro', 'Compinche', 13, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('LINEA FLECKY + FULLCAT', 'subrubro', 'Flecky', 12, 'libre', null, null, null, true, 'El unico FULLCAT del catalogo (10244) esta en el subrubro Flecky y es un fraccionado X KG. Con Flecky alcanza.'),
  ('LINEA FLECKY + FULLCAT', 'subrubro', 'Flecky', 13, 'promo_general', 10, 'bulto', 'pedido', true, 'El unico FULLCAT del catalogo (10244) esta en el subrubro Flecky y es un fraccionado X KG. Con Flecky alcanza.'),
  ('LINEA COMPLETE', 'subrubro', 'Complete', 12, 'libre', null, null, null, true, null),
  ('LINEA COMPLETE', 'subrubro', 'Complete', 13, 'libre', null, null, null, true, null),
  ('LINEA BALANCED', 'subrubro', 'Balanced', 12, 'libre', null, null, null, true, null),
  ('LINEA BALANCED', 'subrubro', 'Balanced', 13, 'libre', null, null, null, true, null),
  ('LINEA PREMIUM', 'subrubro', 'Premium', 12, 'libre', null, null, null, true, 'Subrubro "Premium" (9 arts). Distinto de "Exact Premium" (6), que va en la fila EXCAT PREMIUM.'),
  ('LINEA PREMIUM', 'subrubro', 'Premium', 13, 'libre', null, null, null, true, 'Subrubro "Premium" (9 arts). Distinto de "Exact Premium" (6), que va en la fila EXCAT PREMIUM.'),
  ('LINEA 9 LIVE', 'subrubro', '9 lives', 12, 'libre', null, null, null, true, null),
  ('LINEA 9 LIVE', 'subrubro', '9 lives', 13, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('LINEA 9 LIVE', 'subrubro', '9 lives', 14, 'min', 5, 'bulto', 'linea', true, null),
  ('LINEA CHEF CAT', 'subrubro', 'Chef Cat', 12, 'libre', null, null, null, true, null),
  ('LINEA CHEF CAT', 'subrubro', 'Chef Cat', 13, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('LINEA CHEF CAT', 'subrubro', 'Chef Cat', 14, 'min', 5, 'bulto', 'linea', true, null),
  ('CEREALES DESYUNO', 'subrubro', 'Cereales para desayuno', 12, 'libre', null, null, null, true, 'Subrubro "Cereales para desayuno" (35 arts: almohaditas, anillos de miel, granolas). NO el subrubro "Cereales", que son las semillas a granel.'),
  ('CEREALES DESYUNO', 'subrubro', 'Cereales para desayuno', 13, 'min', 5, 'bulto', 'linea', true, 'Subrubro "Cereales para desayuno" (35 arts: almohaditas, anillos de miel, granolas). NO el subrubro "Cereales", que son las semillas a granel.'),
  ('CEREALES DESYUNO', 'subrubro', 'Cereales para desayuno', 14, 'min', 10, 'bulto', 'linea', true, 'Subrubro "Cereales para desayuno" (35 arts: almohaditas, anillos de miel, granolas). NO el subrubro "Cereales", que son las semillas a granel.'),
  ('CEREALES DESYUNO', 'subrubro', 'Cereales para desayuno', 15, 'min', 30, 'bulto', 'linea', true, 'Subrubro "Cereales para desayuno" (35 arts: almohaditas, anillos de miel, granolas). NO el subrubro "Cereales", que son las semillas a granel.'),
  ('ALPISTE', 'articulo', '400', 12, 'max', 20, 'kg', 'articulo', true, null),
  ('ALPISTE', 'articulo', '400', 13, 'min', 20, 'kg', 'articulo', true, null),
  ('ALPISTE', 'articulo', '400', 14, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('LINO', 'articulo', '401', 12, 'max', 20, 'kg', 'articulo', true, null),
  ('LINO', 'articulo', '401', 13, 'min', 20, 'kg', 'articulo', true, null),
  ('LINO', 'articulo', '401', 14, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('MIJO', 'articulo', '402', 12, 'max', 20, 'kg', 'articulo', true, null),
  ('MIJO', 'articulo', '402', 13, 'min', 20, 'kg', 'articulo', true, null),
  ('MIJO', 'articulo', '402', 14, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('SORGO', 'articulo', '403', 12, 'max', 20, 'kg', 'articulo', true, null),
  ('SORGO', 'articulo', '403', 13, 'min', 20, 'kg', 'articulo', true, null),
  ('SORGO', 'articulo', '403', 14, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('SOJA', 'articulo', '404', 12, 'max', 20, 'kg', 'articulo', false, 'Hay 5 arts con SOJA: 404 SOJA, 411 texturizada, 552 expeller, 560 desactivada. La regla aplica solo al 404?'),
  ('SOJA', 'articulo', '404', 13, 'min', 20, 'kg', 'articulo', false, 'Hay 5 arts con SOJA: 404 SOJA, 411 texturizada, 552 expeller, 560 desactivada. La regla aplica solo al 404?'),
  ('SOJA', 'articulo', '404', 14, 'promo_general', 10, 'bulto', 'pedido', false, 'Hay 5 arts con SOJA: 404 SOJA, 411 texturizada, 552 expeller, 560 desactivada. La regla aplica solo al 404?'),
  ('SESAMO', 'articulo', '405', 12, 'max', 20, 'kg', 'articulo', true, null),
  ('SESAMO', 'articulo', '405', 13, 'min', 20, 'kg', 'articulo', true, null),
  ('SESAMO', 'articulo', '405', 14, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('MIX SEMILLAS', 'articulo', '406', 12, 'max', 20, 'kg', 'articulo', true, 'Art 406 MIX SEMILLAS (subrubro Cereales). El 10460 MIX SEMILLAS SAN JUAN es de la sucursal, queda afuera.'),
  ('MIX SEMILLAS', 'articulo', '406', 13, 'min', 20, 'kg', 'articulo', true, 'Art 406 MIX SEMILLAS (subrubro Cereales). El 10460 MIX SEMILLAS SAN JUAN es de la sucursal, queda afuera.'),
  ('MIX SEMILLAS', 'articulo', '406', 14, 'promo_general', 10, 'bulto', 'pedido', true, 'Art 406 MIX SEMILLAS (subrubro Cereales). El 10460 MIX SEMILLAS SAN JUAN es de la sucursal, queda afuera.'),
  ('QUINOA', 'articulo', '407', 12, 'max', 20, 'kg', 'articulo', false, 'Art 407 QUINOA (granel). Existe tambien 300 QUINOA POP X 3 KG, que esta en Cereales para desayuno y llevaria otra regla. Confirmar.'),
  ('QUINOA', 'articulo', '407', 13, 'min', 20, 'kg', 'articulo', false, 'Art 407 QUINOA (granel). Existe tambien 300 QUINOA POP X 3 KG, que esta en Cereales para desayuno y llevaria otra regla. Confirmar.'),
  ('QUINOA', 'articulo', '407', 14, 'promo_general', 10, 'bulto', 'pedido', false, 'Art 407 QUINOA (granel). Existe tambien 300 QUINOA POP X 3 KG, que esta en Cereales para desayuno y llevaria otra regla. Confirmar.'),
  ('SALVADO DE AVENA', 'articulo', '409', 12, 'max', 20, 'kg', 'articulo', true, null),
  ('SALVADO DE AVENA', 'articulo', '409', 13, 'min', 20, 'kg', 'articulo', true, null),
  ('SALVADO DE AVENA', 'articulo', '409', 14, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('SALVADO DE TRIGO', 'articulo', '410', 12, 'max', 20, 'kg', 'articulo', true, null),
  ('SALVADO DE TRIGO', 'articulo', '410', 13, 'min', 20, 'kg', 'articulo', true, null),
  ('SALVADO DE TRIGO', 'articulo', '410', 14, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('AFRECHO', 'articulo', '451', 12, 'libre', null, null, null, true, 'Art 451, cargado en IM como Bolsas de 30 kg.'),
  ('AFRECHO', 'articulo', '451', 13, 'promo_general', 10, 'bulto', 'pedido', true, 'Art 451, cargado en IM como Bolsas de 30 kg.'),
  ('AFRECHO', 'articulo', '451', 14, 'min', 30, 'bulto', 'articulo', true, 'Art 451, cargado en IM como Bolsas de 30 kg.'),
  ('AFRECHO', 'articulo', '451', 15, 'min', 50, 'bulto', 'articulo', true, 'Art 451, cargado en IM como Bolsas de 30 kg.'),
  ('ARVEJA PARTIDA', 'articulo', '452', 12, 'max', 20, 'kg', 'articulo', true, null),
  ('ARVEJA PARTIDA', 'articulo', '452', 13, 'min', 20, 'kg', 'articulo', true, null),
  ('ARVEJA PARTIDA', 'articulo', '452', 14, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('AVENA FORRAJERA X KG', 'articulo', '453', 12, 'min', 20, 'kg', 'articulo', true, 'Art 453 AVENA FORRAJERA X KG (subrubro Forrajes). Mati 26/08 confirmo que esta fila NO tiene lista 2, quedo corrida pero esta bien.'),
  ('AVENA FORRAJERA X KG', 'articulo', '453', 14, 'promo_general', 10, 'bulto', 'pedido', true, 'Art 453 AVENA FORRAJERA X KG (subrubro Forrajes). Mati 26/08 confirmo que esta fila NO tiene lista 2, quedo corrida pero esta bien.'),
  ('AVENA PELADA', 'articulo', '454', 12, 'max', 20, 'kg', 'articulo', true, 'Art 454 AVENA PELADA (subrubro Forrajes).'),
  ('AVENA PELADA', 'articulo', '454', 13, 'min', 20, 'kg', 'articulo', true, 'Art 454 AVENA PELADA (subrubro Forrajes).'),
  ('AVENA PELADA', 'articulo', '454', 14, 'promo_general', 10, 'bulto', 'pedido', true, 'Art 454 AVENA PELADA (subrubro Forrajes).'),
  ('CARTAMO', 'articulo', '455', 12, 'max', 20, 'kg', 'articulo', true, null),
  ('CARTAMO', 'articulo', '455', 13, 'min', 20, 'kg', 'articulo', true, null),
  ('CARTAMO', 'articulo', '455', 14, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('COLZA', 'articulo', '456', 12, 'max', 20, 'kg', 'articulo', true, null),
  ('COLZA', 'articulo', '456', 13, 'min', 20, 'kg', 'articulo', true, null),
  ('COLZA', 'articulo', '456', 14, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('GIRASOL CHICO', 'articulo', '457', 12, 'max', 20, 'kg', 'articulo', true, 'Art 457. La fila esta duplicada en la planilla (Mati 26/08: ignorar la repetida).'),
  ('GIRASOL CHICO', 'articulo', '457', 13, 'min', 20, 'kg', 'articulo', true, 'Art 457. La fila esta duplicada en la planilla (Mati 26/08: ignorar la repetida).'),
  ('GIRASOL CHICO', 'articulo', '457', 14, 'promo_general', 10, 'bulto', 'pedido', true, 'Art 457. La fila esta duplicada en la planilla (Mati 26/08: ignorar la repetida).'),
  ('GIRASOL GRANDE', 'articulo', '458', 12, 'max', 20, 'kg', 'articulo', true, null),
  ('GIRASOL GRANDE', 'articulo', '458', 13, 'min', 20, 'kg', 'articulo', true, null),
  ('GIRASOL GRANDE', 'articulo', '458', 14, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('GIRASOL PELADO', 'articulo', '459', 12, 'max', 20, 'kg', 'articulo', true, null),
  ('GIRASOL PELADO', 'articulo', '459', 13, 'min', 20, 'kg', 'articulo', true, null),
  ('GIRASOL PELADO', 'articulo', '459', 14, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('MEZCLAS', 'subrubro', 'Mezclas', 12, 'max', 10, 'kg', 'articulo', true, null),
  ('MEZCLAS', 'subrubro', 'Mezclas', 13, 'min', 10, 'kg', 'articulo', true, null),
  ('MEZCLAS', 'subrubro', 'Mezclas', 14, 'min', 10, 'kg', 'articulo', true, null),
  ('PELLET DE TRIGO', 'articulo', '471', 12, 'libre', null, null, null, true, null),
  ('PELLET DE TRIGO', 'articulo', '471', 13, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('TRIGO FORRAJERO', 'articulo', '473', 12, 'libre', null, null, null, true, 'Art 473 TRIGO FORRAJERO X KG (subrubro Forrajes).'),
  ('TRIGO FORRAJERO', 'articulo', '473', 13, 'promo_general', 10, 'bulto', 'pedido', true, 'Art 473 TRIGO FORRAJERO X KG (subrubro Forrajes).'),
  ('LINEA QUEBRADOS', 'subrubro', 'Quebrados', 12, 'libre', null, null, null, true, null),
  ('LINEA QUEBRADOS', 'subrubro', 'Quebrados', 13, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('LINEA QUEBRADOS', 'subrubro', 'Quebrados', 14, 'min', 30, 'bulto', 'linea', true, null),
  ('PELLET ALFA', 'articulo', '485', 12, 'libre', null, null, null, true, null),
  ('PELLET ALFA', 'articulo', '485', 13, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('PELLET ALFA', 'articulo', '10456', 12, 'libre', null, null, null, true, null),
  ('PELLET ALFA', 'articulo', '10456', 13, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('CONDIMENTOS', 'subrubro', 'Condimentos', 12, 'max', 10, 'kg', 'articulo', true, null),
  ('CONDIMENTOS', 'subrubro', 'Condimentos', 13, 'min', 10, 'kg', 'articulo', true, null),
  ('CONDIMENTOS', 'subrubro', 'Condimentos', 14, 'min', 15, 'kg', 'articulo', true, null),
  ('FRUTOS SECOS', 'subrubro', 'Frutos secos', 12, 'max', 5, 'kg', 'articulo', true, 'Partido en IM por mayuscula/minuscula: "Frutos secos" (22) + "Frutos Secos" (2). Se toman los dos.'),
  ('FRUTOS SECOS', 'subrubro', 'Frutos secos', 13, 'min', 5, 'kg', 'articulo', true, 'Partido en IM por mayuscula/minuscula: "Frutos secos" (22) + "Frutos Secos" (2). Se toman los dos.'),
  ('FRUTOS SECOS', 'subrubro', 'Frutos secos', 14, 'min', 10, 'kg', 'articulo', true, 'Partido en IM por mayuscula/minuscula: "Frutos secos" (22) + "Frutos Secos" (2). Se toman los dos.'),
  ('FRUTOS SECOS', 'subrubro', 'Frutos Secos', 12, 'max', 5, 'kg', 'articulo', true, 'Partido en IM por mayuscula/minuscula: "Frutos secos" (22) + "Frutos Secos" (2). Se toman los dos.'),
  ('FRUTOS SECOS', 'subrubro', 'Frutos Secos', 13, 'min', 5, 'kg', 'articulo', true, 'Partido en IM por mayuscula/minuscula: "Frutos secos" (22) + "Frutos Secos" (2). Se toman los dos.'),
  ('FRUTOS SECOS', 'subrubro', 'Frutos Secos', 14, 'min', 10, 'kg', 'articulo', true, 'Partido en IM por mayuscula/minuscula: "Frutos secos" (22) + "Frutos Secos" (2). Se toman los dos.'),
  ('GALLETAS PITUSAS', 'subrubro', 'Galletas', 12, 'libre', null, null, null, false, 'El subrubro "Galletas" tiene 28 arts y NO son todas Pitusas (hay Chocolinas, Morochitas, Pepitas, Suavecitas, Saladix, Cofler, gelatina). LIBRE aplica a todas o solo a las Pitusas?'),
  ('PALITO SALADO', 'articulo', '655', 12, 'libre', null, null, null, true, null),
  ('PISTACHO SALADO MK', 'articulo', '2010', 12, 'max', 10, 'kg', 'articulo', false, 'Art 2010. Existe tambien 2013 PISTACHO NATURAL 2X6KG MK: va con la misma regla?'),
  ('PISTACHO SALADO MK', 'articulo', '2010', 13, 'min', 10, 'kg', 'articulo', false, 'Art 2010. Existe tambien 2013 PISTACHO NATURAL 2X6KG MK: va con la misma regla?'),
  ('ROCKLETS', 'articulo', '13128', 12, 'libre', null, null, null, true, null),
  ('ROCKLETS', 'articulo', '13128', 13, 'libre', null, null, null, true, null),
  ('PASTAS MANI KING', 'subrubro', 'Pastas de Mani', 12, 'libre', null, null, null, false, 'Subrubro "Pastas de Mani" (11 arts). Las 2 filas de PASTA DE MANI BORIS estan adentro de ese subrubro o son aparte?'),
  ('PASTAS MANI KING', 'subrubro', 'Pastas de Mani', 13, 'min', 10, 'bulto', 'articulo', false, 'Subrubro "Pastas de Mani" (11 arts). Las 2 filas de PASTA DE MANI BORIS estan adentro de ese subrubro o son aparte?'),
  ('ARROZ', 'articulo', '700', 12, 'max', 25, 'kg', 'articulo', true, 'Arroz comestible: art 700 (subrubro Legumbres). Distinto de ARROZ P PARRO, que es el de perro.'),
  ('ARROZ', 'articulo', '700', 13, 'min', 25, 'kg', 'articulo', true, 'Arroz comestible: art 700 (subrubro Legumbres). Distinto de ARROZ P PARRO, que es el de perro.'),
  ('ARROZ', 'articulo', '700', 14, 'promo_general', 10, 'bulto', 'pedido', true, 'Arroz comestible: art 700 (subrubro Legumbres). Distinto de ARROZ P PARRO, que es el de perro.'),
  ('FRACCIONADOS KING Y NUTRIFOOD', 'subrubro', 'Fraccionado', 12, 'libre', null, null, null, true, null),
  ('LEGUMBRES (salvo polenta y harina de trigo)', 'subrubro', 'Legumbres', 12, 'max', 20, 'kg', 'articulo', true, 'Mati 26/08: la planilla tenia un error, decia "harina de trigo" pero era "harina de maiz". La HARINA DE TRIGO lleva las condiciones de las legumbres (no se excluye). Los unicos que salen aparte son POLENTA (722) y HARINA DE MAIZ (716), que tienen regla propia por codigo.'),
  ('LEGUMBRES (salvo polenta y harina de trigo)', 'subrubro', 'Legumbres', 13, 'min', 20, 'kg', 'articulo', true, 'Mati 26/08: la planilla tenia un error, decia "harina de trigo" pero era "harina de maiz". La HARINA DE TRIGO lleva las condiciones de las legumbres (no se excluye). Los unicos que salen aparte son POLENTA (722) y HARINA DE MAIZ (716), que tienen regla propia por codigo.'),
  ('LEGUMBRES (salvo polenta y harina de trigo)', 'subrubro', 'Legumbres', 14, 'promo_general', 10, 'bulto', 'pedido', true, 'Mati 26/08: la planilla tenia un error, decia "harina de trigo" pero era "harina de maiz". La HARINA DE TRIGO lleva las condiciones de las legumbres (no se excluye). Los unicos que salen aparte son POLENTA (722) y HARINA DE MAIZ (716), que tienen regla propia por codigo.'),
  ('POLENTA Y HARINA DE MAIZ', 'articulo', '722', 12, 'max', 10, 'kg', 'articulo', true, 'Mati 26/08: a partir de 10 kg recien le pueden hacer lista 2 (el techo es L2). La planilla repetia la misma condicion en L3, se ignora esa columna. Por codigo y no por subrubro: en IM POLENTA (722) y HARINA DE MAIZ (716) viven en el subrubro Legumbres, no en Maiz.'),
  ('POLENTA Y HARINA DE MAIZ', 'articulo', '722', 13, 'min', 10, 'kg', 'articulo', true, 'Mati 26/08: a partir de 10 kg recien le pueden hacer lista 2 (el techo es L2). La planilla repetia la misma condicion en L3, se ignora esa columna. Por codigo y no por subrubro: en IM POLENTA (722) y HARINA DE MAIZ (716) viven en el subrubro Legumbres, no en Maiz.'),
  ('POLENTA Y HARINA DE MAIZ', 'articulo', '716', 12, 'max', 10, 'kg', 'articulo', true, 'Mati 26/08: a partir de 10 kg recien le pueden hacer lista 2 (el techo es L2). La planilla repetia la misma condicion en L3, se ignora esa columna. Por codigo y no por subrubro: en IM POLENTA (722) y HARINA DE MAIZ (716) viven en el subrubro Legumbres, no en Maiz.'),
  ('POLENTA Y HARINA DE MAIZ', 'articulo', '716', 13, 'min', 10, 'kg', 'articulo', true, 'Mati 26/08: a partir de 10 kg recien le pueden hacer lista 2 (el techo es L2). La planilla repetia la misma condicion en L3, se ignora esa columna. Por codigo y no por subrubro: en IM POLENTA (722) y HARINA DE MAIZ (716) viven en el subrubro Legumbres, no en Maiz.'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Perros y Gatos', 12, 'libre', null, null, null, false, 'Junte los 6 subrubros de Accesorios + los 4 de Venenos = 397 articulos. Van TODOS con LIBRE en L1-L3?'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Perros y Gatos', 13, 'libre', null, null, null, false, 'Junte los 6 subrubros de Accesorios + los 4 de Venenos = 397 articulos. Van TODOS con LIBRE en L1-L3?'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Perros y Gatos', 14, 'libre', null, null, null, false, 'Junte los 6 subrubros de Accesorios + los 4 de Venenos = 397 articulos. Van TODOS con LIBRE en L1-L3?'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Plantas', 12, 'libre', null, null, null, false, 'Junte los 6 subrubros de Accesorios + los 4 de Venenos = 397 articulos. Van TODOS con LIBRE en L1-L3?'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Plantas', 13, 'libre', null, null, null, false, 'Junte los 6 subrubros de Accesorios + los 4 de Venenos = 397 articulos. Van TODOS con LIBRE en L1-L3?'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Plantas', 14, 'libre', null, null, null, false, 'Junte los 6 subrubros de Accesorios + los 4 de Venenos = 397 articulos. Van TODOS con LIBRE en L1-L3?'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Aves', 12, 'libre', null, null, null, false, 'Junte los 6 subrubros de Accesorios + los 4 de Venenos = 397 articulos. Van TODOS con LIBRE en L1-L3?'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Aves', 13, 'libre', null, null, null, false, 'Junte los 6 subrubros de Accesorios + los 4 de Venenos = 397 articulos. Van TODOS con LIBRE en L1-L3?'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Aves', 14, 'libre', null, null, null, false, 'Junte los 6 subrubros de Accesorios + los 4 de Venenos = 397 articulos. Van TODOS con LIBRE en L1-L3?'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Peces', 12, 'libre', null, null, null, false, 'Junte los 6 subrubros de Accesorios + los 4 de Venenos = 397 articulos. Van TODOS con LIBRE en L1-L3?'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Peces', 13, 'libre', null, null, null, false, 'Junte los 6 subrubros de Accesorios + los 4 de Venenos = 397 articulos. Van TODOS con LIBRE en L1-L3?'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Peces', 14, 'libre', null, null, null, false, 'Junte los 6 subrubros de Accesorios + los 4 de Venenos = 397 articulos. Van TODOS con LIBRE en L1-L3?'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Hamsters', 12, 'libre', null, null, null, false, 'Junte los 6 subrubros de Accesorios + los 4 de Venenos = 397 articulos. Van TODOS con LIBRE en L1-L3?'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Hamsters', 13, 'libre', null, null, null, false, 'Junte los 6 subrubros de Accesorios + los 4 de Venenos = 397 articulos. Van TODOS con LIBRE en L1-L3?'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Hamsters', 14, 'libre', null, null, null, false, 'Junte los 6 subrubros de Accesorios + los 4 de Venenos = 397 articulos. Van TODOS con LIBRE en L1-L3?'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Animales Granja', 12, 'libre', null, null, null, false, 'Junte los 6 subrubros de Accesorios + los 4 de Venenos = 397 articulos. Van TODOS con LIBRE en L1-L3?'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Animales Granja', 13, 'libre', null, null, null, false, 'Junte los 6 subrubros de Accesorios + los 4 de Venenos = 397 articulos. Van TODOS con LIBRE en L1-L3?'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Animales Granja', 14, 'libre', null, null, null, false, 'Junte los 6 subrubros de Accesorios + los 4 de Venenos = 397 articulos. Van TODOS con LIBRE en L1-L3?'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Venenos Insectos', 12, 'libre', null, null, null, false, 'Junte los 6 subrubros de Accesorios + los 4 de Venenos = 397 articulos. Van TODOS con LIBRE en L1-L3?'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Venenos Insectos', 13, 'libre', null, null, null, false, 'Junte los 6 subrubros de Accesorios + los 4 de Venenos = 397 articulos. Van TODOS con LIBRE en L1-L3?'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Venenos Insectos', 14, 'libre', null, null, null, false, 'Junte los 6 subrubros de Accesorios + los 4 de Venenos = 397 articulos. Van TODOS con LIBRE en L1-L3?'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Venenos Ratas', 12, 'libre', null, null, null, false, 'Junte los 6 subrubros de Accesorios + los 4 de Venenos = 397 articulos. Van TODOS con LIBRE en L1-L3?'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Venenos Ratas', 13, 'libre', null, null, null, false, 'Junte los 6 subrubros de Accesorios + los 4 de Venenos = 397 articulos. Van TODOS con LIBRE en L1-L3?'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Venenos Ratas', 14, 'libre', null, null, null, false, 'Junte los 6 subrubros de Accesorios + los 4 de Venenos = 397 articulos. Van TODOS con LIBRE en L1-L3?'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Venenos Hormigas', 12, 'libre', null, null, null, false, 'Junte los 6 subrubros de Accesorios + los 4 de Venenos = 397 articulos. Van TODOS con LIBRE en L1-L3?'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Venenos Hormigas', 13, 'libre', null, null, null, false, 'Junte los 6 subrubros de Accesorios + los 4 de Venenos = 397 articulos. Van TODOS con LIBRE en L1-L3?'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Venenos Hormigas', 14, 'libre', null, null, null, false, 'Junte los 6 subrubros de Accesorios + los 4 de Venenos = 397 articulos. Van TODOS con LIBRE en L1-L3?'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Venenos Moscas y Cucarachas', 12, 'libre', null, null, null, false, 'Junte los 6 subrubros de Accesorios + los 4 de Venenos = 397 articulos. Van TODOS con LIBRE en L1-L3?'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Venenos Moscas y Cucarachas', 13, 'libre', null, null, null, false, 'Junte los 6 subrubros de Accesorios + los 4 de Venenos = 397 articulos. Van TODOS con LIBRE en L1-L3?'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Venenos Moscas y Cucarachas', 14, 'libre', null, null, null, false, 'Junte los 6 subrubros de Accesorios + los 4 de Venenos = 397 articulos. Van TODOS con LIBRE en L1-L3?'),
  ('PIEDRAS SANITARIAS x20 KG', 'articulo', '1009', 12, 'max', 5, 'bulto', 'articulo', true, null),
  ('PIEDRAS SANITARIAS x20 KG', 'articulo', '1009', 13, 'min', 5, 'bulto', 'articulo', true, null),
  ('PIEDRAS SANITARIAS x20 KG', 'articulo', '1009', 14, 'min', 50, 'bulto', 'articulo', true, null),
  ('PIEDRAS SANITARIAS x20 KG', 'articulo', '1009', 15, 'min', 70, 'bulto', 'articulo', true, null),
  ('PIEDRAS SANITARIAS MI NINO X 12,5 KG', 'articulo', '995', 12, 'max', 5, 'bulto', 'articulo', true, null),
  ('PIEDRAS SANITARIAS MI NINO X 12,5 KG', 'articulo', '995', 13, 'min', 5, 'bulto', 'articulo', true, null),
  ('PIEDRAS SANITARIAS MI NINO X 12,5 KG', 'articulo', '995', 14, 'min', 50, 'bulto', 'articulo', true, null),
  ('PIEDRAS SANITARIAS MI NINO X 12,5 KG', 'articulo', '995', 15, 'min', 120, 'bulto', 'articulo', true, null),
  ('PIEDRAS SANITARIAS MI NINO X 25 KG', 'articulo', '961', 12, 'max', 5, 'bulto', 'articulo', false, 'En IM el art 961 se llama "PIEDRAS SANITARIAS X 25KG", sin MI NINO. Es el mismo producto?'),
  ('PIEDRAS SANITARIAS MI NINO X 25 KG', 'articulo', '961', 13, 'min', 5, 'bulto', 'articulo', false, 'En IM el art 961 se llama "PIEDRAS SANITARIAS X 25KG", sin MI NINO. Es el mismo producto?'),
  ('PIEDRAS SANITARIAS MI NINO X 25 KG', 'articulo', '961', 14, 'min', 50, 'bulto', 'articulo', false, 'En IM el art 961 se llama "PIEDRAS SANITARIAS X 25KG", sin MI NINO. Es el mismo producto?'),
  ('PIEDRAS SANITARIAS MI NINO X 25 KG', 'articulo', '961', 15, 'min', 60, 'bulto', 'articulo', false, 'En IM el art 961 se llama "PIEDRAS SANITARIAS X 25KG", sin MI NINO. Es el mismo producto?'),
  ('EXACT CRIADORES', 'subrubro', 'Exact Criadores', 12, 'libre', null, null, null, true, null),
  ('EXACT CRIADORES', 'subrubro', 'Exact Criadores', 13, 'libre', null, null, null, true, null),
  ('EXACT CRIADORES', 'subrubro', 'Exact Criadores', 14, 'libre', null, null, null, true, null),
  ('EXCAT PREMIUM', 'subrubro', 'Exact Premium', 12, 'libre', null, null, null, true, 'Typo de la planilla: es EXACT PREMIUM, subrubro "Exact Premium" (6 arts). NO "Premium".'),
  ('EXCAT PREMIUM', 'subrubro', 'Exact Premium', 13, 'libre', null, null, null, true, 'Typo de la planilla: es EXACT PREMIUM, subrubro "Exact Premium" (6 arts). NO "Premium".'),
  ('EXCAT PREMIUM', 'subrubro', 'Exact Premium', 14, 'libre', null, null, null, true, 'Typo de la planilla: es EXACT PREMIUM, subrubro "Exact Premium" (6 arts). NO "Premium".'),
  ('SNACKS TIERNITOS', 'articulo', '190', 12, 'libre', null, null, null, true, 'Los 2 snacks en caja del catalogo: 190 (DENTAL R. MEDIANA X 20U) y 191 (DENTAL R. PEQUENA X 30U). Por codigo, para separarlos del alimento Tiernito que comparte subrubro.'),
  ('SNACKS TIERNITOS', 'articulo', '191', 12, 'libre', null, null, null, true, 'Los 2 snacks en caja del catalogo: 190 (DENTAL R. MEDIANA X 20U) y 191 (DENTAL R. PEQUENA X 30U). Por codigo, para separarlos del alimento Tiernito que comparte subrubro.'),
  ('LINEA KEN-L', 'subrubro', 'Ken-L', 12, 'libre', null, null, null, true, null),
  ('LINEA KEN-L', 'subrubro', 'Ken-L', 13, 'libre', null, null, null, true, null),
  ('LINEA KEN-L', 'subrubro', 'Ken-L', 14, 'libre', null, null, null, true, null),
  ('PELLET SANITARIO', 'articulo', '1010', 12, 'libre', null, null, null, false, 'Art 1010. La L3 (5 unidades del mismo producto) es MAS FACIL de alcanzar que la L2 (10 bultos). Es intencional?'),
  ('PELLET SANITARIO', 'articulo', '1010', 13, 'promo_general', 10, 'bulto', 'pedido', false, 'Art 1010. La L3 (5 unidades del mismo producto) es MAS FACIL de alcanzar que la L2 (10 bultos). Es intencional?'),
  ('PELLET SANITARIO', 'articulo', '1010', 14, 'min', 5, 'bulto', 'articulo', false, 'Art 1010. La L3 (5 unidades del mismo producto) es MAS FACIL de alcanzar que la L2 (10 bultos). Es intencional?'),
  ('FORRAJES VARIOS', 'articulo', '13818', 12, 'excluido', null, null, null, true, 'Mati 26/08: se usa para facturar a consumidor final, se excluye de todos los circuitos. Es el articulo mas facturado de Casa Central (308 renglones en 3 semanas, todos en L1).'),
  ('COSTO DE DISTRIBUCION', 'articulo', '13819', 12, 'excluido', null, null, null, true, 'No es un producto sino un cargo de flete que se factura como renglon (28 renglones en 3 semanas). No lleva lista.')
on conflict (tenant_id, match_tipo, match_valor, cod_lista) do update set
  nombre = excluded.nombre, condicion = excluded.condicion, umbral = excluded.umbral,
  unidad = excluded.unidad, ambito = excluded.ambito, activo = excluded.activo,
  nota = excluded.nota, updated_at = now();
