-- Migration 035 — Reglas de lista según la planilla real de Mati (08/09/2026).
-- GENERADO por scripts/gen-listas-seed-v2.mjs. NO editar a mano: corregir el script.
--
-- Qué cambia respecto de lo cargado en agosto:
--   · LINEA FLECKY + FULLCAT gana L3 (20 unidades surtidas) y L4 (30). Antes llegaba
--     sólo hasta L2, y la auditoría del 08/09 encontró 193 renglones vendidos en L4.
--   · MEZCLAS se parte en dos: las comunes siguen con 20 kg y las de gallo, gallo
--     premium y gruesa pasan a 10 kg.
--   · Entran 13 líneas que no estaban: los maníes y snacks de Mani King, PASTA DE MANI
--     BORIS, PISTACHO, MONKY, VITALFUN y SALSA TIERNITOS.
--   · Los umbrales en UNIDADES dejan de contarse como bultos (ver el 🪤 del generador).

alter table listas_reglas drop constraint if exists listas_reglas_unidad_check;
alter table listas_reglas add constraint listas_reglas_unidad_check
  check (unidad is null or unidad in ('bulto','kg','unidad'));

-- 🪤 El índice único era (tenant, tipo, valor, lista): UNA sola condición por lista.
-- Varias líneas llegan a la misma lista por dos caminos (la condición propia y la promo
-- general de 10 bultos surtidos), así que la condición entra en la clave.
drop index if exists listas_reglas_target_uidx;
create unique index if not exists listas_reglas_target_uidx
  on listas_reglas (tenant_id, match_tipo, match_valor, cod_lista, condicion);

delete from listas_reglas where tenant_id = '00000000-0000-0000-0000-000000000001' and condicion <> 'excluido';

insert into listas_reglas (nombre, match_tipo, match_valor, cod_lista, condicion, umbral, unidad, ambito, activo, nota) values
  ('LINEA GANAVE', 'subrubro', 'Ganave', 12, 'libre', null, null, null, true, null),
  ('LINEA GANAVE', 'subrubro', 'Ganave', 13, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('CONEJO GEPSA', 'subrubro', 'Gepsa', 12, 'libre', null, null, null, true, null),
  ('CONEJO GEPSA', 'subrubro', 'Gepsa', 13, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('CONEJO GEPSA', 'subrubro', 'Gepsa', 14, 'min', 10, 'unidad', 'articulo', true, null),
  ('CONEJO GEPSA', 'subrubro', 'Gepsa', 15, 'min', 30, 'unidad', 'articulo', true, null),
  ('CONEJO COENCAR', 'subrubro', 'Conecar', 12, 'libre', null, null, null, true, null),
  ('CONEJO COENCAR', 'subrubro', 'Conecar', 13, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('CONEJO COENCAR', 'subrubro', 'Conecar', 14, 'min', 10, 'unidad', 'articulo', true, null),
  ('CONEJO COENCAR', 'subrubro', 'Conecar', 15, 'min', 30, 'unidad', 'articulo', true, null),
  ('LINEA PRODUCCION PROPIA SEMILLERO', 'subrubro', 'Semillero', 12, 'libre', null, null, null, true, null),
  ('LINEA PRODUCCION PROPIA SEMILLERO', 'subrubro', 'Semillero', 13, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('LINEA PRODUCCION PROPIA SEMILLERO', 'subrubro', 'Semillero', 14, 'min', 30, 'unidad', 'linea', true, null),
  ('LINEA PRODUCCION PROPIA SEMILLERO', 'subrubro', 'Semillero', 15, 'min', 50, 'unidad', 'linea', true, null),
  ('LINEA ROSCO', 'subrubro', 'Rosco', 12, 'libre', null, null, null, true, null),
  ('LINEA ROSCO', 'subrubro', 'Rosco', 13, 'libre', null, null, null, true, null),
  ('LINEA ROSCO', 'subrubro', 'Rosco', 14, 'libre', null, null, null, true, null),
  ('LINEA TIERNITO', 'subrubro', 'Tiernitos', 12, 'libre', null, null, null, true, null),
  ('LINEA TIERNITO', 'subrubro', 'Tiernito', 12, 'libre', null, null, null, true, null),
  ('LINEA TIERNITO', 'subrubro', 'Tiernitos', 13, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('LINEA TIERNITO', 'subrubro', 'Tiernito', 13, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('LINEA TIERNITO', 'subrubro', 'Tiernitos', 14, 'min', 5, 'unidad', 'linea', true, null),
  ('LINEA TIERNITO', 'subrubro', 'Tiernito', 14, 'min', 5, 'unidad', 'linea', true, null),
  ('LINEA DS CRIADORES', 'subrubro', 'Dog Seleccion', 12, 'libre', null, null, null, true, null),
  ('LINEA DS CRIADORES', 'subrubro', 'Dog Seleccion', 13, 'libre', null, null, null, true, null),
  ('LINEA DS CRIADORES', 'subrubro', 'Dog Seleccion', 14, 'libre', null, null, null, true, null),
  ('LINEA GRAN CAMPEON', 'subrubro', 'Gran Campeon', 12, 'libre', null, null, null, true, null),
  ('LINEA GRAN CAMPEON', 'subrubro', 'Gran Campeon', 13, 'libre', null, null, null, true, null),
  ('LINEA GRAN CAMPEON', 'subrubro', 'Gran Campeon', 14, 'libre', null, null, null, true, null),
  ('LINEA PACHA', 'subrubro', 'Pacha', 12, 'libre', null, null, null, true, null),
  ('LINEA PACHA', 'subrubro', 'Pacha', 13, 'libre', null, null, null, true, null),
  ('LINEA BELCAN', 'subrubro', 'Belcan', 12, 'libre', null, null, null, true, null),
  ('LINEA BELCAN', 'subrubro', 'Belcat', 12, 'libre', null, null, null, true, null),
  ('LINEA BELCAN', 'subrubro', 'Belcan', 13, 'libre', null, null, null, true, null),
  ('LINEA BELCAN', 'subrubro', 'Belcat', 13, 'libre', null, null, null, true, null),
  ('LINEA BELCAN', 'subrubro', 'Belcan', 14, 'libre', null, null, null, true, null),
  ('LINEA BELCAN', 'subrubro', 'Belcat', 14, 'libre', null, null, null, true, null),
  ('LINEA BELCAN', 'subrubro', 'Belcan', 15, 'libre', null, null, null, true, null),
  ('LINEA BELCAN', 'subrubro', 'Belcat', 15, 'libre', null, null, null, true, null),
  ('LINEA ZIMPI', 'subrubro', 'Zimpi', 12, 'libre', null, null, null, true, null),
  ('LINEA ZIMPI', 'subrubro', 'Zimpy', 12, 'libre', null, null, null, true, null),
  ('LINEA ZIMPI', 'subrubro', 'Zimpi', 13, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('LINEA ZIMPI', 'subrubro', 'Zimpy', 13, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('LINEA ZIMPI', 'subrubro', 'Zimpi', 14, 'min', 5, 'unidad', 'linea', true, null),
  ('LINEA ZIMPI', 'subrubro', 'Zimpy', 14, 'min', 5, 'unidad', 'linea', true, null),
  ('LINEA ZIMPI', 'subrubro', 'Zimpi', 15, 'min', 20, 'unidad', 'linea', true, null),
  ('LINEA ZIMPI', 'subrubro', 'Zimpy', 15, 'min', 20, 'unidad', 'linea', true, null),
  ('ARROZ P PARRO', 'subrubro', 'Arroz p/perro', 12, 'libre', null, null, null, true, null),
  ('ARROZ P PARRO', 'subrubro', 'Arroz p/perro', 13, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('COMPINCHE', 'subrubro', 'Compinche', 12, 'libre', null, null, null, true, null),
  ('COMPINCHE', 'subrubro', 'Compinche', 13, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('LINEA FLECKY + FULLCAT', 'subrubro', 'Flecky', 12, 'libre', null, null, null, true, null),
  ('LINEA FLECKY + FULLCAT', 'subrubro', 'Flecky', 13, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('LINEA FLECKY + FULLCAT', 'subrubro', 'Flecky', 14, 'min', 20, 'unidad', 'linea', true, null),
  ('LINEA FLECKY + FULLCAT', 'subrubro', 'Flecky', 15, 'min', 30, 'unidad', 'linea', true, null),
  ('LINEA COMPLETE', 'subrubro', 'Complete', 12, 'libre', null, null, null, true, null),
  ('LINEA COMPLETE', 'subrubro', 'Complete', 13, 'libre', null, null, null, true, null),
  ('LINEA BALANCED', 'subrubro', 'Balanced', 12, 'libre', null, null, null, true, null),
  ('LINEA BALANCED', 'subrubro', 'Balanced', 13, 'libre', null, null, null, true, null),
  ('LINEA PREMIUM', 'subrubro', 'Premium', 12, 'libre', null, null, null, true, null),
  ('LINEA PREMIUM', 'subrubro', 'Premium', 13, 'libre', null, null, null, true, null),
  ('LINEA 9 LIVE', 'subrubro', '9 lives', 12, 'libre', null, null, null, true, null),
  ('LINEA 9 LIVE', 'subrubro', '9 lives', 13, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('LINEA 9 LIVE', 'subrubro', '9 lives', 14, 'min', 5, 'unidad', 'linea', true, null),
  ('LINEA CHEF CAT', 'subrubro', 'Chef Cat', 12, 'libre', null, null, null, true, null),
  ('LINEA CHEF CAT', 'subrubro', 'Chef Cat', 13, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('LINEA CHEF CAT', 'subrubro', 'Chef Cat', 14, 'min', 5, 'unidad', 'linea', true, null),
  ('CEREALES DESYUNO', 'subrubro', 'Cereales para desayuno', 12, 'libre', null, null, null, true, 'Nota de la planilla: aclarar los faltantes habilitan la venta sin requerimiento de listas'),
  ('CEREALES DESYUNO', 'subrubro', 'Cereales para desayuno', 13, 'min', 5, 'unidad', 'linea', true, 'Nota de la planilla: aclarar los faltantes habilitan la venta sin requerimiento de listas'),
  ('CEREALES DESYUNO', 'subrubro', 'Cereales para desayuno', 14, 'min', 10, 'unidad', 'linea', true, 'Nota de la planilla: aclarar los faltantes habilitan la venta sin requerimiento de listas'),
  ('CEREALES DESYUNO', 'subrubro', 'Cereales para desayuno', 15, 'min', 30, 'unidad', 'linea', true, 'Nota de la planilla: aclarar los faltantes habilitan la venta sin requerimiento de listas'),
  ('ALPISTE', 'articulo', '400', 12, 'max', 20, 'kg', 'articulo', true, null),
  ('ALPISTE', 'articulo', '400', 13, 'min', 20, 'kg', 'articulo', true, null),
  ('ALPISTE', 'articulo', '400', 14, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('LINO', 'articulo', '401', 12, 'max', 20, 'kg', 'articulo', true, null),
  ('LINO', 'articulo', '401', 13, 'min', 20, 'kg', 'articulo', true, null),
  ('LINO', 'articulo', '401', 14, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('MIJO', 'articulo', '402', 12, 'max', 20, 'kg', 'articulo', true, null),
  ('MIJO', 'articulo', '402', 13, 'min', 20, 'kg', 'articulo', true, null),
  ('MIJO', 'articulo', '402', 14, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('SORGO', 'articulo', '403', 12, 'max', 20, 'kg', 'articulo', true, null),
  ('SORGO', 'articulo', '403', 13, 'min', 20, 'kg', 'articulo', true, null),
  ('SORGO', 'articulo', '403', 14, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('SOJA', 'articulo', '404', 12, 'max', 20, 'kg', 'articulo', true, null),
  ('SOJA', 'articulo', '404', 13, 'min', 20, 'kg', 'articulo', true, null),
  ('SOJA', 'articulo', '404', 14, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('SESAMO', 'articulo', '405', 12, 'max', 20, 'kg', 'articulo', true, null),
  ('SESAMO', 'articulo', '405', 13, 'min', 20, 'kg', 'articulo', true, null),
  ('SESAMO', 'articulo', '405', 14, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('MIX SEMILLAS', 'articulo', '406', 12, 'max', 20, 'kg', 'articulo', true, null),
  ('MIX SEMILLAS', 'articulo', '406', 13, 'min', 20, 'kg', 'articulo', true, null),
  ('MIX SEMILLAS', 'articulo', '406', 14, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('QUINOA', 'articulo', '407', 12, 'max', 20, 'kg', 'articulo', true, null),
  ('QUINOA', 'articulo', '407', 13, 'min', 20, 'kg', 'articulo', true, null),
  ('QUINOA', 'articulo', '407', 14, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('SALVADO DE AVENA', 'articulo', '409', 12, 'max', 20, 'kg', 'articulo', true, null),
  ('SALVADO DE AVENA', 'articulo', '409', 13, 'min', 20, 'kg', 'articulo', true, null),
  ('SALVADO DE AVENA', 'articulo', '409', 14, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('SALVADO DE TRIGO', 'articulo', '410', 12, 'max', 20, 'kg', 'articulo', true, null),
  ('SALVADO DE TRIGO', 'articulo', '410', 13, 'min', 20, 'kg', 'articulo', true, null),
  ('SALVADO DE TRIGO', 'articulo', '410', 14, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('AFRECHO', 'articulo', '451', 12, 'libre', null, null, null, true, null),
  ('AFRECHO', 'articulo', '451', 13, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('AFRECHO', 'articulo', '451', 14, 'min', 30, 'unidad', 'articulo', true, null),
  ('AFRECHO', 'articulo', '451', 15, 'min', 50, 'unidad', 'articulo', true, null),
  ('ARVEJA PARTIDA', 'articulo', '452', 12, 'max', 20, 'kg', 'articulo', true, null),
  ('ARVEJA PARTIDA', 'articulo', '452', 13, 'min', 20, 'kg', 'articulo', true, null),
  ('ARVEJA PARTIDA', 'articulo', '452', 14, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('AVENA FORRAJERA X KG', 'articulo', '453', 12, 'min', 20, 'kg', 'articulo', true, null),
  ('AVENA FORRAJERA X KG', 'articulo', '453', 14, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('AVENA PELADA', 'articulo', '454', 12, 'max', 20, 'kg', 'articulo', true, null),
  ('AVENA PELADA', 'articulo', '454', 13, 'min', 20, 'kg', 'articulo', true, null),
  ('AVENA PELADA', 'articulo', '454', 14, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('CARTAMO', 'articulo', '455', 12, 'max', 20, 'kg', 'articulo', true, null),
  ('CARTAMO', 'articulo', '455', 13, 'min', 20, 'kg', 'articulo', true, null),
  ('CARTAMO', 'articulo', '455', 14, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('COLZA', 'articulo', '456', 12, 'max', 20, 'kg', 'articulo', true, null),
  ('COLZA', 'articulo', '456', 13, 'min', 20, 'kg', 'articulo', true, null),
  ('COLZA', 'articulo', '456', 14, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('GIRASOL CHICO', 'articulo', '457', 12, 'max', 20, 'kg', 'articulo', true, null),
  ('GIRASOL CHICO', 'articulo', '457', 13, 'min', 20, 'kg', 'articulo', true, null),
  ('GIRASOL CHICO', 'articulo', '457', 14, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('GIRASOL GRANDE', 'articulo', '458', 12, 'max', 20, 'kg', 'articulo', true, null),
  ('GIRASOL GRANDE', 'articulo', '458', 13, 'min', 20, 'kg', 'articulo', true, null),
  ('GIRASOL GRANDE', 'articulo', '458', 14, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('GIRASOL PELADO', 'articulo', '459', 12, 'max', 20, 'kg', 'articulo', true, null),
  ('GIRASOL PELADO', 'articulo', '459', 13, 'min', 20, 'kg', 'articulo', true, null),
  ('GIRASOL PELADO', 'articulo', '459', 14, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('MEZCLAS (salvo gallo, gallo premium y gruesa)', 'subrubro', 'Mezclas', 12, 'max', 20, 'kg', 'articulo', true, null),
  ('MEZCLAS (salvo gallo, gallo premium y gruesa)', 'subrubro', 'Mezclas', 13, 'min', 20, 'kg', 'articulo', true, null),
  ('MEZCLAS (salvo gallo, gallo premium y gruesa)', 'subrubro', 'Mezclas', 14, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('PELLET DE TRIGO', 'articulo', '471', 12, 'libre', null, null, null, true, null),
  ('PELLET DE TRIGO', 'articulo', '471', 13, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('TRIGO FORRAJERO', 'articulo', '473', 12, 'libre', null, null, null, true, null),
  ('TRIGO FORRAJERO', 'articulo', '473', 13, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('LINEA QUEBRADOS', 'subrubro', 'Quebrados', 12, 'libre', null, null, null, true, null),
  ('LINEA QUEBRADOS', 'subrubro', 'Quebrados', 13, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('LINEA QUEBRADOS', 'subrubro', 'Quebrados', 14, 'min', 10, 'unidad', 'linea', true, null),
  ('PELLET ALFA', 'articulo', '485', 12, 'libre', null, null, null, true, null),
  ('PELLET ALFA', 'articulo', '10456', 12, 'libre', null, null, null, true, null),
  ('PELLET ALFA', 'articulo', '485', 13, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('PELLET ALFA', 'articulo', '10456', 13, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('CONDIMENTOS', 'subrubro', 'Condimentos', 12, 'max', 10, 'kg', 'articulo', true, null),
  ('CONDIMENTOS', 'subrubro', 'Condimentos', 13, 'min', 10, 'kg', 'articulo', true, null),
  ('CONDIMENTOS', 'subrubro', 'Condimentos', 14, 'min', 15, 'kg', 'articulo', true, null),
  ('FRUTOS SECOS', 'subrubro', 'Frutos secos', 12, 'max', 5, 'kg', 'articulo', true, null),
  ('FRUTOS SECOS', 'subrubro', 'Frutos Secos', 12, 'max', 5, 'kg', 'articulo', true, null),
  ('FRUTOS SECOS', 'subrubro', 'Frutos secos', 13, 'min', 5, 'kg', 'articulo', true, null),
  ('FRUTOS SECOS', 'subrubro', 'Frutos Secos', 13, 'min', 5, 'kg', 'articulo', true, null),
  ('FRUTOS SECOS', 'subrubro', 'Frutos secos', 14, 'min', 10, 'kg', 'articulo', true, null),
  ('FRUTOS SECOS', 'subrubro', 'Frutos Secos', 14, 'min', 10, 'kg', 'articulo', true, null),
  ('GALLETAS PITUSAS', 'subrubro', 'Galletas', 12, 'libre', null, null, null, true, null),
  ('MONKY', 'articulo', '695', 12, 'libre', null, null, null, true, null),
  ('MONKY', 'articulo', '696', 12, 'libre', null, null, null, true, null),
  ('MONKY', 'articulo', '697', 12, 'libre', null, null, null, true, null),
  ('MONKY', 'articulo', '698', 12, 'libre', null, null, null, true, null),
  ('MONKY', 'articulo', '699', 12, 'libre', null, null, null, true, null),
  ('MONKY', 'articulo', '727', 12, 'libre', null, null, null, true, null),
  ('MONKY', 'articulo', '13123', 12, 'libre', null, null, null, true, null),
  ('MONKY', 'articulo', '13124', 12, 'libre', null, null, null, true, null),
  ('MONKY', 'articulo', '13125', 12, 'libre', null, null, null, true, null),
  ('MONKY', 'articulo', '13126', 12, 'libre', null, null, null, true, null),
  ('MONKY', 'articulo', '13127', 12, 'libre', null, null, null, true, null),
  ('MANI C/ CHOCOLATE', 'articulo', '650', 12, 'libre', null, null, null, true, null),
  ('MANI C/ CHOCOLATE', 'articulo', '10707', 12, 'libre', null, null, null, true, null),
  ('MANI SABORIZADO', 'articulo', '652', 12, 'libre', null, null, null, true, null),
  ('MANI SABORIZADO', 'articulo', '772', 12, 'libre', null, null, null, true, null),
  ('MANI SABORIZADO', 'articulo', '773', 12, 'libre', null, null, null, true, null),
  ('MANI SABORIZADO', 'articulo', '774', 12, 'libre', null, null, null, true, null),
  ('MANI SABORIZADO', 'articulo', '775', 12, 'libre', null, null, null, true, null),
  ('MANI SABORIZADO', 'articulo', '10682', 12, 'libre', null, null, null, true, null),
  ('MANI SABORIZADO', 'articulo', '10683', 12, 'libre', null, null, null, true, null),
  ('MANI SABORIZADO', 'articulo', '10684', 12, 'libre', null, null, null, true, null),
  ('MANI SABORIZADO', 'articulo', '10685', 12, 'libre', null, null, null, true, null),
  ('MANI SABORIZADO', 'articulo', '10686', 12, 'libre', null, null, null, true, null),
  ('MANI SABORIZADO', 'articulo', '10690', 12, 'libre', null, null, null, true, null),
  ('MANI SABORIZADO', 'articulo', '10708', 12, 'libre', null, null, null, true, null),
  ('MANI SALADO CON PIEL', 'articulo', '653', 12, 'libre', null, null, null, true, null),
  ('PALITO SALADO', 'articulo', '655', 12, 'libre', null, null, null, true, null),
  ('MANI SALADO X KG - Mani King', 'articulo', '10672', 12, 'max', 10, 'kg', 'articulo', true, null),
  ('MANI SALADO X KG - Mani King', 'articulo', '10672', 13, 'min', 10, 'kg', 'articulo', true, null),
  ('MANI TOSTADO X KG - Mani King', 'articulo', '10670', 12, 'max', 10, 'kg', 'articulo', true, null),
  ('MANI TOSTADO X KG - Mani King', 'articulo', '10670', 13, 'min', 10, 'kg', 'articulo', true, null),
  ('MANI TOSTADO C/ CASCARA X KG - Mani King', 'articulo', '10669', 12, 'max', 5, 'kg', 'articulo', true, 'Sólo el fraccionado por kilo (MANI CON CASCARA KING X KG); los 16x175 y 10x400 son otra presentación.'),
  ('MANI TOSTADO C/ CASCARA X KG - Mani King', 'articulo', '10669', 13, 'min', 10, 'kg', 'articulo', true, 'Sólo el fraccionado por kilo (MANI CON CASCARA KING X KG); los 16x175 y 10x400 son otra presentación.'),
  ('PRALINE X KG - Mani King', 'articulo', '10671', 12, 'max', 10, 'kg', 'articulo', true, null),
  ('PRALINE X KG - Mani King', 'articulo', '10671', 13, 'min', 10, 'kg', 'articulo', true, null),
  ('PASTA DE MANI DULCE BORIS X 400G X 12U', 'articulo', '692', 12, 'libre', null, null, null, true, null),
  ('PASTA DE MANI DULCE BORIS X 400G X 12U', 'articulo', '692', 13, 'libre', null, null, null, true, null),
  ('PASTA DE MANI CHOCO BORIS X 400G X 12U', 'articulo', '693', 12, 'libre', null, null, null, true, null),
  ('PASTA DE MANI CHOCO BORIS X 400G X 12U', 'articulo', '693', 13, 'libre', null, null, null, true, null),
  ('PISTACHO SALADO MK', 'articulo', '2010', 12, 'max', 10, 'kg', 'articulo', true, 'Sólo el salado; PISTACHO NATURAL 2X6KG (2013) no figura en la planilla.'),
  ('PISTACHO SALADO MK', 'articulo', '2010', 13, 'min', 10, 'kg', 'articulo', true, 'Sólo el salado; PISTACHO NATURAL 2X6KG (2013) no figura en la planilla.'),
  ('ROCKLETS', 'articulo', '13128', 12, 'libre', null, null, null, true, null),
  ('ROCKLETS', 'articulo', '13128', 13, 'libre', null, null, null, true, null),
  ('PASTAS MANI KING', 'subrubro', 'Pastas de Mani', 12, 'libre', null, null, null, true, null),
  ('PASTAS MANI KING', 'subrubro', 'Pastas de Mani', 13, 'min', 10, 'unidad', 'articulo', true, null),
  ('ARROZ', 'articulo', '700', 12, 'max', 25, 'kg', 'articulo', true, null),
  ('ARROZ', 'articulo', '700', 13, 'min', 25, 'kg', 'articulo', true, null),
  ('ARROZ', 'articulo', '700', 14, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('FRACCIONADOS KING Y NUTRIFOOD', 'subrubro', 'Fraccionado', 12, 'libre', null, null, null, true, null),
  ('LEGUMBRES (salvo polenta y harina de trigo)', 'subrubro', 'Legumbres', 12, 'max', 20, 'kg', 'articulo', true, null),
  ('LEGUMBRES (salvo polenta y harina de trigo)', 'subrubro', 'Legumbres', 13, 'min', 20, 'kg', 'articulo', true, null),
  ('LEGUMBRES (salvo polenta y harina de trigo)', 'subrubro', 'Legumbres', 14, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('POLENTA Y HARINA DE MAIZ', 'articulo', '722', 12, 'max', 10, 'kg', 'articulo', true, 'Nota de la planilla: no lo esta interpretando'),
  ('POLENTA Y HARINA DE MAIZ', 'articulo', '716', 12, 'max', 10, 'kg', 'articulo', true, 'Nota de la planilla: no lo esta interpretando'),
  ('POLENTA Y HARINA DE MAIZ', 'articulo', '722', 13, 'min', 10, 'kg', 'articulo', true, 'Nota de la planilla: no lo esta interpretando'),
  ('POLENTA Y HARINA DE MAIZ', 'articulo', '716', 13, 'min', 10, 'kg', 'articulo', true, 'Nota de la planilla: no lo esta interpretando'),
  ('POLENTA Y HARINA DE MAIZ', 'articulo', '722', 14, 'min', 10, 'kg', 'articulo', true, 'Nota de la planilla: no lo esta interpretando'),
  ('POLENTA Y HARINA DE MAIZ', 'articulo', '716', 14, 'min', 10, 'kg', 'articulo', true, 'Nota de la planilla: no lo esta interpretando'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Perros y Gatos', 12, 'libre', null, null, null, true, null),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Plantas', 12, 'libre', null, null, null, true, null),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Aves', 12, 'libre', null, null, null, true, null),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Peces', 12, 'libre', null, null, null, true, null),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Hamsters', 12, 'libre', null, null, null, true, null),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Animales Granja', 12, 'libre', null, null, null, true, null),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Venenos Insectos', 12, 'libre', null, null, null, true, null),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Venenos Ratas', 12, 'libre', null, null, null, true, null),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Venenos Hormigas', 12, 'libre', null, null, null, true, null),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Venenos Moscas y Cucarachas', 12, 'libre', null, null, null, true, null),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Perros y Gatos', 13, 'libre', null, null, null, true, null),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Plantas', 13, 'libre', null, null, null, true, null),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Aves', 13, 'libre', null, null, null, true, null),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Peces', 13, 'libre', null, null, null, true, null),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Hamsters', 13, 'libre', null, null, null, true, null),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Animales Granja', 13, 'libre', null, null, null, true, null),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Venenos Insectos', 13, 'libre', null, null, null, true, null),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Venenos Ratas', 13, 'libre', null, null, null, true, null),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Venenos Hormigas', 13, 'libre', null, null, null, true, null),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Venenos Moscas y Cucarachas', 13, 'libre', null, null, null, true, null),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Perros y Gatos', 14, 'libre', null, null, null, true, null),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Plantas', 14, 'libre', null, null, null, true, null),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Aves', 14, 'libre', null, null, null, true, null),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Peces', 14, 'libre', null, null, null, true, null),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Hamsters', 14, 'libre', null, null, null, true, null),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Animales Granja', 14, 'libre', null, null, null, true, null),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Venenos Insectos', 14, 'libre', null, null, null, true, null),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Venenos Ratas', 14, 'libre', null, null, null, true, null),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Venenos Hormigas', 14, 'libre', null, null, null, true, null),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Venenos Moscas y Cucarachas', 14, 'libre', null, null, null, true, null),
  ('PIEDRAS SANITARIAS x20 KG', 'articulo', '1009', 12, 'max', 5, 'unidad', 'articulo', true, null),
  ('PIEDRAS SANITARIAS x20 KG', 'articulo', '1009', 13, 'min', 5, 'unidad', 'articulo', true, null),
  ('PIEDRAS SANITARIAS x20 KG', 'articulo', '1009', 14, 'min', 50, 'bulto', 'articulo', true, null),
  ('PIEDRAS SANITARIAS x20 KG', 'articulo', '1009', 15, 'min', 70, 'bulto', 'articulo', true, null),
  ('PIEDRAS SANITARIAS MI NINO X 12,5 KG', 'articulo', '995', 12, 'max', 5, 'unidad', 'articulo', true, null),
  ('PIEDRAS SANITARIAS MI NINO X 12,5 KG', 'articulo', '995', 13, 'min', 5, 'unidad', 'articulo', true, null),
  ('PIEDRAS SANITARIAS MI NINO X 12,5 KG', 'articulo', '995', 14, 'min', 50, 'bulto', 'articulo', true, null),
  ('PIEDRAS SANITARIAS MI NINO X 12,5 KG', 'articulo', '995', 15, 'min', 120, 'bulto', 'articulo', true, null),
  ('PIEDRAS SANITARIAS MI NINO X 25 KG', 'articulo', '961', 12, 'max', 5, 'unidad', 'articulo', true, null),
  ('PIEDRAS SANITARIAS MI NINO X 25 KG', 'articulo', '961', 13, 'min', 5, 'unidad', 'articulo', true, null),
  ('PIEDRAS SANITARIAS MI NINO X 25 KG', 'articulo', '961', 14, 'min', 50, 'bulto', 'articulo', true, null),
  ('PIEDRAS SANITARIAS MI NINO X 25 KG', 'articulo', '961', 15, 'min', 60, 'bulto', 'articulo', true, null),
  ('EXACT CRIADORES', 'subrubro', 'Exact Criadores', 12, 'libre', null, null, null, true, 'Nota de la planilla: 5% de descuento habilitado sonre lista 1'),
  ('EXACT CRIADORES', 'subrubro', 'Exact Criadores', 13, 'libre', null, null, null, true, 'Nota de la planilla: 5% de descuento habilitado sonre lista 1'),
  ('EXACT CRIADORES', 'subrubro', 'Exact Criadores', 14, 'libre', null, null, null, true, 'Nota de la planilla: 5% de descuento habilitado sonre lista 1'),
  ('EXCAT PREMIUM', 'subrubro', 'Exact Premium', 12, 'libre', null, null, null, true, null),
  ('EXCAT PREMIUM', 'subrubro', 'Exact Premium', 13, 'libre', null, null, null, true, null),
  ('EXCAT PREMIUM', 'subrubro', 'Exact Premium', 14, 'libre', null, null, null, true, null),
  ('VITALFUN', 'articulo', '1016', 12, 'libre', null, null, null, true, 'ARENA SANITARIA VITAL FUN X 6K. Vive en Accesorios Perros y Gatos, así que va por código: la regla por artículo le gana a la de la línea.'),
  ('VITALFUN', 'articulo', '1016', 13, 'min', 5, 'unidad', 'articulo', true, 'ARENA SANITARIA VITAL FUN X 6K. Vive en Accesorios Perros y Gatos, así que va por código: la regla por artículo le gana a la de la línea.'),
  ('SNACKS TIERNITOS', 'articulo', '190', 12, 'libre', null, null, null, true, null),
  ('SNACKS TIERNITOS', 'articulo', '191', 12, 'libre', null, null, null, true, null),
  ('SALSA TIERNITOS', 'articulo', '194', 12, 'libre', null, null, null, true, 'Comparte subrubro con el alimento Tiernito, por eso va por código.'),
  ('SALSA TIERNITOS', 'articulo', '195', 12, 'libre', null, null, null, true, 'Comparte subrubro con el alimento Tiernito, por eso va por código.'),
  ('SALSA TIERNITOS', 'articulo', '196', 12, 'libre', null, null, null, true, 'Comparte subrubro con el alimento Tiernito, por eso va por código.'),
  ('SALSA TIERNITOS', 'articulo', '10264', 12, 'libre', null, null, null, true, 'Comparte subrubro con el alimento Tiernito, por eso va por código.'),
  ('SALSA TIERNITOS', 'articulo', '10265', 12, 'libre', null, null, null, true, 'Comparte subrubro con el alimento Tiernito, por eso va por código.'),
  ('LINEA KEN-L', 'subrubro', 'Ken-L', 12, 'libre', null, null, null, true, null),
  ('LINEA KEN-L', 'subrubro', 'Ken-L', 13, 'libre', null, null, null, true, null),
  ('LINEA KEN-L', 'subrubro', 'Ken-L', 14, 'libre', null, null, null, true, null),
  ('PELLET SANITARIO', 'articulo', '1010', 12, 'libre', null, null, null, true, null),
  ('PELLET SANITARIO', 'articulo', '1010', 13, 'promo_general', 10, 'bulto', 'pedido', true, null),
  ('PELLET SANITARIO', 'articulo', '1010', 14, 'min', 5, 'unidad', 'articulo', true, null),
  ('MEZCLAS GALLO, GALLO PREMIUM Y GRUESA', 'articulo', '464', 12, 'max', 10, 'kg', 'articulo', true, null),
  ('MEZCLAS GALLO, GALLO PREMIUM Y GRUESA', 'articulo', '468', 12, 'max', 10, 'kg', 'articulo', true, null),
  ('MEZCLAS GALLO, GALLO PREMIUM Y GRUESA', 'articulo', '469', 12, 'max', 10, 'kg', 'articulo', true, null),
  ('MEZCLAS GALLO, GALLO PREMIUM Y GRUESA', 'articulo', '491', 12, 'max', 10, 'kg', 'articulo', true, null),
  ('MEZCLAS GALLO, GALLO PREMIUM Y GRUESA', 'articulo', '464', 13, 'min', 10, 'kg', 'articulo', true, null),
  ('MEZCLAS GALLO, GALLO PREMIUM Y GRUESA', 'articulo', '468', 13, 'min', 10, 'kg', 'articulo', true, null),
  ('MEZCLAS GALLO, GALLO PREMIUM Y GRUESA', 'articulo', '469', 13, 'min', 10, 'kg', 'articulo', true, null),
  ('MEZCLAS GALLO, GALLO PREMIUM Y GRUESA', 'articulo', '491', 13, 'min', 10, 'kg', 'articulo', true, null),
  ('MEZCLAS GALLO, GALLO PREMIUM Y GRUESA', 'articulo', '464', 14, 'min', 10, 'kg', 'articulo', true, null),
  ('MEZCLAS GALLO, GALLO PREMIUM Y GRUESA', 'articulo', '468', 14, 'min', 10, 'kg', 'articulo', true, null),
  ('MEZCLAS GALLO, GALLO PREMIUM Y GRUESA', 'articulo', '469', 14, 'min', 10, 'kg', 'articulo', true, null),
  ('MEZCLAS GALLO, GALLO PREMIUM Y GRUESA', 'articulo', '491', 14, 'min', 10, 'kg', 'articulo', true, null),
  ('VICIA', 'articulo', '474', 12, 'max', 20, 'kg', 'articulo', true, '⚠️ HEREDADA: la línea no figura en la planilla del 08/09/2026. Se conserva para no dejarla sin control; confirmar con Mati.'),
  ('VICIA', 'articulo', '474', 13, 'min', 20, 'kg', 'articulo', true, '⚠️ HEREDADA: la línea no figura en la planilla del 08/09/2026. Se conserva para no dejarla sin control; confirmar con Mati.'),
  ('VICIA', 'articulo', '474', 14, 'promo_general', 10, 'bulto', 'pedido', true, '⚠️ HEREDADA: la línea no figura en la planilla del 08/09/2026. Se conserva para no dejarla sin control; confirmar con Mati.'),
  ('VITAMINA', 'articulo', '475', 12, 'max', 20, 'kg', 'articulo', true, '⚠️ HEREDADA: la línea no figura en la planilla del 08/09/2026. Se conserva para no dejarla sin control; confirmar con Mati.'),
  ('VITAMINA', 'articulo', '475', 13, 'min', 20, 'kg', 'articulo', true, '⚠️ HEREDADA: la línea no figura en la planilla del 08/09/2026. Se conserva para no dejarla sin control; confirmar con Mati.'),
  ('VITAMINA', 'articulo', '475', 14, 'promo_general', 10, 'bulto', 'pedido', true, '⚠️ HEREDADA: la línea no figura en la planilla del 08/09/2026. Se conserva para no dejarla sin control; confirmar con Mati.'),
  ('MAIZ CUARENTIN', 'articulo', '461', 12, 'max', 20, 'kg', 'articulo', true, '⚠️ HEREDADA: la línea no figura en la planilla del 08/09/2026. Se conserva para no dejarla sin control; confirmar con Mati.'),
  ('MAIZ CUARENTIN', 'articulo', '461', 13, 'min', 20, 'kg', 'articulo', true, '⚠️ HEREDADA: la línea no figura en la planilla del 08/09/2026. Se conserva para no dejarla sin control; confirmar con Mati.');

insert into descuentos_reglas (nombre, match_tipo, match_valor, desde_cantidad, ambito, porcentaje_max, requiere_lista, requiere_mejor_lista, aviso, activo) values
  ('EXACT CRIADORES', 'subrubro', 'Exact Criadores', 1, 'articulo', 5, 12, false, null, true)
on conflict (tenant_id, match_tipo, match_valor, desde_cantidad, coalesce(requiere_lista, -1)) do update set
  porcentaje_max = excluded.porcentaje_max, ambito = excluded.ambito, activo = excluded.activo;
