-- Migration 035 — Reglas de lista según la planilla CORREGIDA por Mati (08/09/2026).
-- GENERADO por scripts/gen-listas-seed-v2.mjs. NO editar a mano: corregir el script y regenerar.
--
-- Reemplaza la carga de las migraciones 021/022/025, que traducía mal la notación de la
-- planilla. Los tres errores que corrige, detectados en la auditoría del 08/09:
--   1. "10+1" se había leído como la promo general de 10 bultos surtidos. Es una
--      bonificación: se carga como 11 unidades en la lista 2.
--   2. "BOLSA" se había leído como "20 kg", que dejaba afuera las bolsas de 25 y 30 kg.
--   3. "BOLS +10%" y "BOLSA" habían quedado con la MISMA condición, así que la lista 2
--      era inalcanzable y todo pedido disparaba "le estás cobrando de más" (110 casos).

alter table listas_reglas add column if not exists opcional boolean not null default false;
alter table listas_reglas add column if not exists bonificacion text;
comment on column listas_reglas.opcional is 'La condición habilita la lista pero no le da derecho al cliente (celda "BOLS +10%").';
comment on column listas_reglas.bonificacion is 'La promo como la escribe la planilla ("10+1"): el umbral ya viene sumado.';
alter table listas_reglas drop constraint if exists listas_reglas_condicion_check;
alter table listas_reglas add constraint listas_reglas_condicion_check
  check (condicion in ('libre','promo_general','min','max','excluido','bulto_cerrado'));

-- Las exclusiones no salen de la planilla: se preservan aparte (ver abajo).
delete from listas_reglas where tenant_id = '00000000-0000-0000-0000-000000000001' and condicion <> 'excluido';

insert into listas_reglas (nombre, match_tipo, match_valor, cod_lista, condicion, umbral, unidad, ambito, opcional, bonificacion, activo, nota) values
  ('GANAVE', 'subrubro', 'Ganave', 12, 'libre', null, null, null, false, null, true, null),
  ('GANAVE', 'subrubro', 'Ganave', 13, 'min', 10, 'bulto', 'linea', false, null, true, null),
  ('GANAVE', 'subrubro', 'Ganave', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('CONEJO AMANECER', 'subrubro', 'El Amanecer', 12, 'libre', null, null, null, false, null, true, null),
  ('CONEJO AMANECER', 'subrubro', 'El Amanecer', 13, 'min', 11, 'bulto', 'linea', false, '10+1', true, null),
  ('CONEJO AMANECER', 'subrubro', 'El Amanecer', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('CONEJO AMANECER', 'subrubro', 'El Amanecer', 14, 'min', 12, 'bulto', 'linea', false, '10+2', true, null),
  ('CONEJO AMANECER', 'subrubro', 'El Amanecer', 15, 'min', 30, 'bulto', 'linea', false, null, true, null),
  ('CONEJO GEPSA', 'subrubro', 'Gepsa', 12, 'libre', null, null, null, false, null, true, null),
  ('CONEJO GEPSA', 'subrubro', 'Gepsa', 13, 'min', 11, 'bulto', 'linea', false, '10+1', true, null),
  ('CONEJO GEPSA', 'subrubro', 'Gepsa', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('CONEJO GEPSA', 'subrubro', 'Gepsa', 14, 'min', 12, 'bulto', 'linea', false, '10+2', true, null),
  ('CONEJO GEPSA', 'subrubro', 'Gepsa', 15, 'min', 30, 'bulto', 'linea', false, null, true, null),
  ('CONEJO COENCAR', 'subrubro', 'Conecar', 12, 'libre', null, null, null, false, null, true, 'La planilla dice COENCAR; en IM el subrubro es "Conecar".'),
  ('CONEJO COENCAR', 'subrubro', 'Conecar', 13, 'min', 11, 'bulto', 'linea', false, '10+1', true, 'La planilla dice COENCAR; en IM el subrubro es "Conecar".'),
  ('CONEJO COENCAR', 'subrubro', 'Conecar', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('CONEJO COENCAR', 'subrubro', 'Conecar', 14, 'min', 12, 'bulto', 'linea', false, '10+2', true, 'La planilla dice COENCAR; en IM el subrubro es "Conecar".'),
  ('CONEJO COENCAR', 'subrubro', 'Conecar', 15, 'min', 30, 'bulto', 'linea', false, null, true, 'La planilla dice COENCAR; en IM el subrubro es "Conecar".'),
  ('BALANCEADOS PROPIOS', 'subrubro', 'Semillero', 12, 'libre', null, null, null, false, null, true, 'Es la línea de producción propia. Los umbrales 30/50 coinciden con los que ya estaban cargados como "LINEA PRODUCCION PROPIA SEMILLERO".'),
  ('BALANCEADOS PROPIOS', 'subrubro', 'Semillero', 13, 'min', 11, 'bulto', 'linea', false, '10+1', true, 'Es la línea de producción propia. Los umbrales 30/50 coinciden con los que ya estaban cargados como "LINEA PRODUCCION PROPIA SEMILLERO".'),
  ('BALANCEADOS PROPIOS', 'subrubro', 'Semillero', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('BALANCEADOS PROPIOS', 'subrubro', 'Semillero', 14, 'min', 30, 'bulto', 'linea', false, null, true, 'Es la línea de producción propia. Los umbrales 30/50 coinciden con los que ya estaban cargados como "LINEA PRODUCCION PROPIA SEMILLERO".'),
  ('BALANCEADOS PROPIOS', 'subrubro', 'Semillero', 15, 'min', 50, 'bulto', 'linea', false, null, true, 'Es la línea de producción propia. Los umbrales 30/50 coinciden con los que ya estaban cargados como "LINEA PRODUCCION PROPIA SEMILLERO".'),
  ('ROSCO', 'subrubro', 'Rosco', 12, 'libre', null, null, null, false, null, true, null),
  ('ROSCO', 'subrubro', 'Rosco', 13, 'min', 10, 'bulto', 'linea', false, null, true, null),
  ('ROSCO', 'subrubro', 'Rosco', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('ROSCO', 'subrubro', 'Rosco', 14, 'min', 20, 'bulto', 'linea', false, null, true, null),
  ('TIERNITO', 'subrubro', 'Tiernitos', 12, 'libre', null, null, null, false, null, true, 'Perro (15/21 kg) y gato (10 kg) viven en subrubros distintos. Los SNACK TIERNITO tienen regla propia por código.'),
  ('TIERNITO', 'subrubro', 'Tiernito', 12, 'libre', null, null, null, false, null, true, 'Perro (15/21 kg) y gato (10 kg) viven en subrubros distintos. Los SNACK TIERNITO tienen regla propia por código.'),
  ('TIERNITO', 'subrubro', 'Tiernitos', 13, 'min', 11, 'bulto', 'linea', false, '10+1', true, 'Perro (15/21 kg) y gato (10 kg) viven en subrubros distintos. Los SNACK TIERNITO tienen regla propia por código.'),
  ('TIERNITO', 'subrubro', 'Tiernito', 13, 'min', 11, 'bulto', 'linea', false, '10+1', true, 'Perro (15/21 kg) y gato (10 kg) viven en subrubros distintos. Los SNACK TIERNITO tienen regla propia por código.'),
  ('TIERNITO', 'subrubro', 'Tiernitos', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('TIERNITO', 'subrubro', 'Tiernito', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('TIERNITO', 'subrubro', 'Tiernitos', 14, 'min', 12, 'bulto', 'linea', false, '10+2', true, 'Perro (15/21 kg) y gato (10 kg) viven en subrubros distintos. Los SNACK TIERNITO tienen regla propia por código.'),
  ('TIERNITO', 'subrubro', 'Tiernito', 14, 'min', 12, 'bulto', 'linea', false, '10+2', true, 'Perro (15/21 kg) y gato (10 kg) viven en subrubros distintos. Los SNACK TIERNITO tienen regla propia por código.'),
  ('DS CRIADORES', 'subrubro', 'Dog Seleccion', 12, 'libre', null, null, null, false, null, true, 'En IM el subrubro es "Dog Seleccion"; los artículos se llaman DS CRIADORES / DS ETIQ.'),
  ('DS CRIADORES', 'subrubro', 'Dog Seleccion', 13, 'min', 11, 'bulto', 'linea', false, '10+1', true, 'En IM el subrubro es "Dog Seleccion"; los artículos se llaman DS CRIADORES / DS ETIQ.'),
  ('DS CRIADORES', 'subrubro', 'Dog Seleccion', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('DS CRIADORES', 'subrubro', 'Dog Seleccion', 14, 'min', 20, 'bulto', 'linea', false, null, true, 'En IM el subrubro es "Dog Seleccion"; los artículos se llaman DS CRIADORES / DS ETIQ.'),
  ('GRAN CAMPEON', 'subrubro', 'Gran Campeon', 12, 'libre', null, null, null, false, null, true, null),
  ('GRAN CAMPEON', 'subrubro', 'Gran Campeon', 13, 'min', 11, 'bulto', 'linea', false, '10+1', true, null),
  ('GRAN CAMPEON', 'subrubro', 'Gran Campeon', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('GRAN CAMPEON', 'subrubro', 'Gran Campeon', 14, 'min', 30, 'bulto', 'linea', false, null, true, null),
  ('PACHA', 'subrubro', 'Pacha', 12, 'libre', null, null, null, false, null, true, null),
  ('PACHA', 'subrubro', 'Pacha', 13, 'min', 11, 'bulto', 'linea', false, '10+1', true, null),
  ('PACHA', 'subrubro', 'Pacha', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('BELCAN', 'subrubro', 'Belcan', 12, 'libre', null, null, null, false, null, true, 'En IM está partido en dos subrubros: Belcan (perro) y Belcat (gato).'),
  ('BELCAN', 'subrubro', 'Belcat', 12, 'libre', null, null, null, false, null, true, 'En IM está partido en dos subrubros: Belcan (perro) y Belcat (gato).'),
  ('BELCAN', 'subrubro', 'Belcan', 13, 'min', 11, 'bulto', 'linea', false, '10+1', true, 'En IM está partido en dos subrubros: Belcan (perro) y Belcat (gato).'),
  ('BELCAN', 'subrubro', 'Belcat', 13, 'min', 11, 'bulto', 'linea', false, '10+1', true, 'En IM está partido en dos subrubros: Belcan (perro) y Belcat (gato).'),
  ('BELCAN', 'subrubro', 'Belcan', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('BELCAN', 'subrubro', 'Belcat', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('BELCAN', 'subrubro', 'Belcan', 14, 'min', 12, 'bulto', 'linea', false, '10+2', true, 'En IM está partido en dos subrubros: Belcan (perro) y Belcat (gato).'),
  ('BELCAN', 'subrubro', 'Belcat', 14, 'min', 12, 'bulto', 'linea', false, '10+2', true, 'En IM está partido en dos subrubros: Belcan (perro) y Belcat (gato).'),
  ('BELCAN', 'subrubro', 'Belcan', 15, 'min', 30, 'bulto', 'linea', false, null, true, 'En IM está partido en dos subrubros: Belcan (perro) y Belcat (gato).'),
  ('BELCAN', 'subrubro', 'Belcat', 15, 'min', 30, 'bulto', 'linea', false, null, true, 'En IM está partido en dos subrubros: Belcan (perro) y Belcat (gato).'),
  ('ZIMPI', 'subrubro', 'Zimpi', 12, 'libre', null, null, null, false, null, true, 'En IM está escrito de las dos formas (Zimpi y Zimpy).'),
  ('ZIMPI', 'subrubro', 'Zimpy', 12, 'libre', null, null, null, false, null, true, 'En IM está escrito de las dos formas (Zimpi y Zimpy).'),
  ('ZIMPI', 'subrubro', 'Zimpi', 13, 'min', 11, 'bulto', 'linea', false, '10+1', true, 'En IM está escrito de las dos formas (Zimpi y Zimpy).'),
  ('ZIMPI', 'subrubro', 'Zimpy', 13, 'min', 11, 'bulto', 'linea', false, '10+1', true, 'En IM está escrito de las dos formas (Zimpi y Zimpy).'),
  ('ZIMPI', 'subrubro', 'Zimpi', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('ZIMPI', 'subrubro', 'Zimpy', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('ZIMPI', 'subrubro', 'Zimpi', 14, 'min', 12, 'bulto', 'linea', false, '10+2', true, 'En IM está escrito de las dos formas (Zimpi y Zimpy).'),
  ('ZIMPI', 'subrubro', 'Zimpy', 14, 'min', 12, 'bulto', 'linea', false, '10+2', true, 'En IM está escrito de las dos formas (Zimpi y Zimpy).'),
  ('ZIMPI', 'subrubro', 'Zimpi', 15, 'min', 30, 'bulto', 'linea', false, null, true, 'En IM está escrito de las dos formas (Zimpi y Zimpy).'),
  ('ZIMPI', 'subrubro', 'Zimpy', 15, 'min', 30, 'bulto', 'linea', false, null, true, 'En IM está escrito de las dos formas (Zimpi y Zimpy).'),
  ('ARROZ P PARRO', 'subrubro', 'Arroz p/perro', 12, 'libre', null, null, null, false, null, true, null),
  ('ARROZ P PARRO', 'subrubro', 'Arroz p/perro', 13, 'min', 11, 'bulto', 'linea', false, '10+1', true, null),
  ('ARROZ P PARRO', 'subrubro', 'Arroz p/perro', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('COMPINCHE', 'subrubro', 'Compinche', 12, 'libre', null, null, null, false, null, true, null),
  ('COMPINCHE', 'subrubro', 'Compinche', 13, 'min', 11, 'bulto', 'linea', false, '10+1', true, null),
  ('COMPINCHE', 'subrubro', 'Compinche', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('COMPINCHE', 'subrubro', 'Compinche', 14, 'min', 12, 'bulto', 'linea', false, '10+2', true, null),
  ('COMPINCHE', 'subrubro', 'Compinche', 15, 'min', 50, 'bulto', 'linea', false, null, true, null),
  ('FLECKY', 'subrubro', 'Flecky', 12, 'libre', null, null, null, false, null, true, 'Incluye FULL CAT, que comparte subrubro. 🔴 La L4 (50 uds) es NUEVA: hasta el 08/09 la línea sólo llegaba a L2 y se vendía en L4 igual (193 renglones, $26,8M en 4 semanas).'),
  ('FLECKY', 'subrubro', 'Flecky', 13, 'min', 11, 'bulto', 'linea', false, '10+1', true, 'Incluye FULL CAT, que comparte subrubro. 🔴 La L4 (50 uds) es NUEVA: hasta el 08/09 la línea sólo llegaba a L2 y se vendía en L4 igual (193 renglones, $26,8M en 4 semanas).'),
  ('FLECKY', 'subrubro', 'Flecky', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('FLECKY', 'subrubro', 'Flecky', 14, 'min', 12, 'bulto', 'linea', false, '10+2', true, 'Incluye FULL CAT, que comparte subrubro. 🔴 La L4 (50 uds) es NUEVA: hasta el 08/09 la línea sólo llegaba a L2 y se vendía en L4 igual (193 renglones, $26,8M en 4 semanas).'),
  ('FLECKY', 'subrubro', 'Flecky', 15, 'min', 50, 'bulto', 'linea', false, null, true, 'Incluye FULL CAT, que comparte subrubro. 🔴 La L4 (50 uds) es NUEVA: hasta el 08/09 la línea sólo llegaba a L2 y se vendía en L4 igual (193 renglones, $26,8M en 4 semanas).'),
  ('COMPLETE', 'subrubro', 'Complete', 12, 'libre', null, null, null, false, null, true, null),
  ('COMPLETE', 'subrubro', 'Complete', 13, 'min', 10, 'bulto', 'linea', false, null, true, null),
  ('COMPLETE', 'subrubro', 'Complete', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('BALANCED', 'subrubro', 'Balanced', 12, 'libre', null, null, null, false, null, true, null),
  ('BALANCED', 'subrubro', 'Balanced', 13, 'min', 10, 'bulto', 'linea', false, null, true, null),
  ('BALANCED', 'subrubro', 'Balanced', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('PREMIUM', 'subrubro', 'Exact Premium', 12, 'libre', null, null, null, false, null, true, null),
  ('PREMIUM', 'subrubro', 'Premium', 12, 'libre', null, null, null, false, null, true, null),
  ('PREMIUM', 'subrubro', 'Exact Premium', 13, 'min', 10, 'bulto', 'linea', false, null, true, null),
  ('PREMIUM', 'subrubro', 'Premium', 13, 'min', 10, 'bulto', 'linea', false, null, true, null),
  ('PREMIUM', 'subrubro', 'Exact Premium', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('PREMIUM', 'subrubro', 'Premium', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('9 LIVE', 'subrubro', '9 lives', 12, 'libre', null, null, null, false, null, true, 'En IM el subrubro se escribe "9 lives".'),
  ('9 LIVE', 'subrubro', '9 lives', 13, 'min', 11, 'bulto', 'linea', false, '10+1', true, 'En IM el subrubro se escribe "9 lives".'),
  ('9 LIVE', 'subrubro', '9 lives', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('9 LIVE', 'subrubro', '9 lives', 14, 'min', 12, 'bulto', 'linea', false, '10+2', true, 'En IM el subrubro se escribe "9 lives".'),
  ('CHEF CAT', 'subrubro', 'Chef Cat', 12, 'libre', null, null, null, false, null, true, null),
  ('CHEF CAT', 'subrubro', 'Chef Cat', 13, 'min', 11, 'bulto', 'linea', false, '10+1', true, null),
  ('CHEF CAT', 'subrubro', 'Chef Cat', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('CHEF CAT', 'subrubro', 'Chef Cat', 14, 'min', 12, 'bulto', 'linea', false, '10+2', true, null),
  ('CEREALES DESYUNO', 'subrubro', 'Cereales para desayuno', 12, 'libre', null, null, null, false, null, true, null),
  ('CEREALES DESYUNO', 'subrubro', 'Cereales para desayuno', 13, 'max', 5, 'bulto', 'linea', false, null, true, null),
  ('CEREALES DESYUNO', 'subrubro', 'Cereales para desayuno', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('CEREALES DESYUNO', 'subrubro', 'Cereales para desayuno', 14, 'min', 5, 'bulto', 'linea', false, null, true, null),
  ('CEREALES DESYUNO', 'subrubro', 'Cereales para desayuno', 15, 'min', 30, 'bulto', 'linea', false, null, true, null),
  ('ALPISTE', 'articulo', '400', 12, 'libre', null, null, null, false, null, true, null),
  ('ALPISTE', 'articulo', '400', 13, 'bulto_cerrado', null, null, null, false, null, true, null),
  ('ALPISTE', 'articulo', '400', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('ALPISTE', 'articulo', '400', 14, 'bulto_cerrado', null, null, null, true, null, true, 'La bolsa habilita esta lista; el 10% extra es decisión del vendedor, no un derecho del cliente.'),
  ('LINO', 'articulo', '401', 12, 'libre', null, null, null, false, null, true, null),
  ('LINO', 'articulo', '401', 13, 'bulto_cerrado', null, null, null, false, null, true, null),
  ('LINO', 'articulo', '401', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('LINO', 'articulo', '401', 14, 'bulto_cerrado', null, null, null, true, null, true, 'La bolsa habilita esta lista; el 10% extra es decisión del vendedor, no un derecho del cliente.'),
  ('MIJO', 'articulo', '402', 12, 'libre', null, null, null, false, null, true, null),
  ('MIJO', 'articulo', '402', 13, 'bulto_cerrado', null, null, null, false, null, true, null),
  ('MIJO', 'articulo', '402', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('MIJO', 'articulo', '402', 14, 'bulto_cerrado', null, null, null, true, null, true, 'La bolsa habilita esta lista; el 10% extra es decisión del vendedor, no un derecho del cliente.'),
  ('SORGO', 'articulo', '403', 12, 'libre', null, null, null, false, null, true, null),
  ('SORGO', 'articulo', '403', 14, 'bulto_cerrado', null, null, null, true, null, true, 'La bolsa habilita esta lista; el 10% extra es decisión del vendedor, no un derecho del cliente.'),
  ('SOJA', 'articulo', '404', 12, 'libre', null, null, null, false, null, true, null),
  ('SOJA', 'articulo', '404', 13, 'bulto_cerrado', null, null, null, false, null, true, null),
  ('SOJA', 'articulo', '404', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('SOJA', 'articulo', '404', 14, 'bulto_cerrado', null, null, null, true, null, true, 'La bolsa habilita esta lista; el 10% extra es decisión del vendedor, no un derecho del cliente.'),
  ('SESAMO', 'articulo', '405', 12, 'libre', null, null, null, false, null, true, null),
  ('SESAMO', 'articulo', '405', 13, 'bulto_cerrado', null, null, null, false, null, true, null),
  ('SESAMO', 'articulo', '405', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('SESAMO', 'articulo', '405', 14, 'bulto_cerrado', null, null, null, true, null, true, 'La bolsa habilita esta lista; el 10% extra es decisión del vendedor, no un derecho del cliente.'),
  ('MIX SEMILLAS', 'articulo', '406', 12, 'libre', null, null, null, false, null, true, null),
  ('MIX SEMILLAS', 'articulo', '406', 13, 'bulto_cerrado', null, null, null, false, null, true, null),
  ('MIX SEMILLAS', 'articulo', '406', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('MIX SEMILLAS', 'articulo', '406', 14, 'bulto_cerrado', null, null, null, true, null, true, 'La bolsa habilita esta lista; el 10% extra es decisión del vendedor, no un derecho del cliente.'),
  ('QUINOA', 'articulo', '407', 12, 'libre', null, null, null, false, null, true, null),
  ('QUINOA', 'articulo', '407', 13, 'bulto_cerrado', null, null, null, false, null, true, null),
  ('QUINOA', 'articulo', '407', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('QUINOA', 'articulo', '407', 14, 'bulto_cerrado', null, null, null, true, null, true, 'La bolsa habilita esta lista; el 10% extra es decisión del vendedor, no un derecho del cliente.'),
  ('SALVADO DE AVENA', 'articulo', '409', 12, 'libre', null, null, null, false, null, true, null),
  ('SALVADO DE AVENA', 'articulo', '409', 13, 'bulto_cerrado', null, null, null, false, null, true, null),
  ('SALVADO DE AVENA', 'articulo', '409', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('SALVADO DE AVENA', 'articulo', '409', 14, 'bulto_cerrado', null, null, null, true, null, true, 'La bolsa habilita esta lista; el 10% extra es decisión del vendedor, no un derecho del cliente.'),
  ('SALVADO DE TRIGO', 'articulo', '410', 12, 'libre', null, null, null, false, null, true, null),
  ('SALVADO DE TRIGO', 'articulo', '410', 13, 'bulto_cerrado', null, null, null, false, null, true, null),
  ('SALVADO DE TRIGO', 'articulo', '410', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('SALVADO DE TRIGO', 'articulo', '410', 14, 'bulto_cerrado', null, null, null, true, null, true, 'La bolsa habilita esta lista; el 10% extra es decisión del vendedor, no un derecho del cliente.'),
  ('AFRECHO', 'articulo', '451', 12, 'libre', null, null, null, false, null, true, null),
  ('AFRECHO', 'articulo', '451', 13, 'min', 11, 'bulto', 'linea', false, '10+1', true, null),
  ('AFRECHO', 'articulo', '451', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('AFRECHO', 'articulo', '451', 14, 'min', 30, 'bulto', 'linea', false, null, true, null),
  ('AFRECHO', 'articulo', '451', 15, 'min', 50, 'bulto', 'linea', false, null, true, null),
  ('ARVEJA PARTIDA', 'articulo', '452', 12, 'libre', null, null, null, false, null, true, null),
  ('ARVEJA PARTIDA', 'articulo', '452', 13, 'bulto_cerrado', null, null, null, false, null, true, null),
  ('ARVEJA PARTIDA', 'articulo', '452', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('ARVEJA PARTIDA', 'articulo', '452', 14, 'bulto_cerrado', null, null, null, true, null, true, 'La bolsa habilita esta lista; el 10% extra es decisión del vendedor, no un derecho del cliente.'),
  ('AVENA FORRAJERA X KG', 'articulo', '453', 12, 'libre', null, null, null, false, null, true, null),
  ('AVENA FORRAJERA X KG', 'articulo', '453', 14, 'bulto_cerrado', null, null, null, true, null, true, 'La bolsa habilita esta lista; el 10% extra es decisión del vendedor, no un derecho del cliente.'),
  ('AVENA PELADA', 'articulo', '454', 12, 'libre', null, null, null, false, null, true, null),
  ('AVENA PELADA', 'articulo', '454', 13, 'bulto_cerrado', null, null, null, false, null, true, null),
  ('AVENA PELADA', 'articulo', '454', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('AVENA PELADA', 'articulo', '454', 14, 'bulto_cerrado', null, null, null, true, null, true, 'La bolsa habilita esta lista; el 10% extra es decisión del vendedor, no un derecho del cliente.'),
  ('CARTAMO', 'articulo', '455', 12, 'libre', null, null, null, false, null, true, null),
  ('CARTAMO', 'articulo', '455', 13, 'bulto_cerrado', null, null, null, false, null, true, null),
  ('CARTAMO', 'articulo', '455', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('CARTAMO', 'articulo', '455', 14, 'bulto_cerrado', null, null, null, true, null, true, 'La bolsa habilita esta lista; el 10% extra es decisión del vendedor, no un derecho del cliente.'),
  ('COLZA', 'articulo', '456', 12, 'libre', null, null, null, false, null, true, null),
  ('COLZA', 'articulo', '456', 13, 'bulto_cerrado', null, null, null, false, null, true, null),
  ('COLZA', 'articulo', '456', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('COLZA', 'articulo', '456', 14, 'bulto_cerrado', null, null, null, true, null, true, 'La bolsa habilita esta lista; el 10% extra es decisión del vendedor, no un derecho del cliente.'),
  ('GIRASOL CHICO', 'articulo', '457', 12, 'libre', null, null, null, false, null, true, null),
  ('GIRASOL CHICO', 'articulo', '457', 13, 'bulto_cerrado', null, null, null, false, null, true, null),
  ('GIRASOL CHICO', 'articulo', '457', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('GIRASOL CHICO', 'articulo', '457', 14, 'bulto_cerrado', null, null, null, true, null, true, 'La bolsa habilita esta lista; el 10% extra es decisión del vendedor, no un derecho del cliente.'),
  ('GIRASOL GRANDE', 'articulo', '458', 12, 'libre', null, null, null, false, null, true, null),
  ('GIRASOL GRANDE', 'articulo', '458', 13, 'bulto_cerrado', null, null, null, false, null, true, null),
  ('GIRASOL GRANDE', 'articulo', '458', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('GIRASOL GRANDE', 'articulo', '458', 14, 'bulto_cerrado', null, null, null, true, null, true, 'La bolsa habilita esta lista; el 10% extra es decisión del vendedor, no un derecho del cliente.'),
  ('GIRASOL PELADO', 'articulo', '459', 12, 'libre', null, null, null, false, null, true, null),
  ('GIRASOL PELADO', 'articulo', '459', 13, 'bulto_cerrado', null, null, null, false, null, true, null),
  ('GIRASOL PELADO', 'articulo', '459', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('GIRASOL PELADO', 'articulo', '459', 14, 'bulto_cerrado', null, null, null, true, null, true, 'La bolsa habilita esta lista; el 10% extra es decisión del vendedor, no un derecho del cliente.'),
  ('MEZCLAS', 'subrubro', 'Mezclas', 12, 'libre', null, null, null, false, null, true, null),
  ('MEZCLAS', 'subrubro', 'Mezclas', 13, 'bulto_cerrado', null, null, null, false, null, true, null),
  ('MEZCLAS', 'subrubro', 'Mezclas', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('MEZCLAS', 'subrubro', 'Mezclas', 14, 'bulto_cerrado', null, null, null, true, null, true, 'La bolsa habilita esta lista; el 10% extra es decisión del vendedor, no un derecho del cliente.'),
  ('PELLET', 'articulo', '471', 12, 'libre', null, null, null, false, null, true, null),
  ('PELLET', 'articulo', '471', 14, 'min', 11, 'bulto', 'linea', false, '10+1', true, null),
  ('TRIGO FORRAJERO', 'articulo', '473', 12, 'libre', null, null, null, false, null, true, null),
  ('TRIGO FORRAJERO', 'articulo', '473', 13, 'min', 11, 'bulto', 'linea', false, '10+1', true, null),
  ('TRIGO FORRAJERO', 'articulo', '473', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('QUEBRADOS', 'subrubro', 'Quebrados', 12, 'libre', null, null, null, false, null, true, null),
  ('QUEBRADOS', 'subrubro', 'Quebrados', 13, 'min', 11, 'bulto', 'linea', false, '10+1', true, null),
  ('QUEBRADOS', 'subrubro', 'Quebrados', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('QUEBRADOS', 'subrubro', 'Quebrados', 14, 'min', 20, 'bulto', 'linea', false, null, true, null),
  ('PELLET ALFA', 'articulo', '485', 12, 'libre', null, null, null, false, null, true, null),
  ('PELLET ALFA', 'articulo', '485', 14, 'min', 11, 'bulto', 'linea', false, '10+1', true, null),
  ('CONDIMENTOS', 'subrubro', 'Condimentos', 12, 'libre', null, null, null, false, null, true, null),
  ('CONDIMENTOS', 'subrubro', 'Condimentos', 13, 'min', 10, 'kg', 'articulo', false, null, true, null),
  ('CONDIMENTOS', 'subrubro', 'Condimentos', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('CONDIMENTOS', 'subrubro', 'Condimentos', 14, 'min', 10, 'bulto', 'linea', false, null, true, null),
  ('FRUTOS SECOS', 'subrubro', 'Frutos secos', 12, 'libre', null, null, null, false, null, true, null),
  ('FRUTOS SECOS', 'subrubro', 'Frutos Secos', 12, 'libre', null, null, null, false, null, true, null),
  ('FRUTOS SECOS', 'subrubro', 'Frutos secos', 13, 'min', 5, 'kg', 'articulo', false, null, true, null),
  ('FRUTOS SECOS', 'subrubro', 'Frutos Secos', 13, 'min', 5, 'kg', 'articulo', false, null, true, null),
  ('FRUTOS SECOS', 'subrubro', 'Frutos secos', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('FRUTOS SECOS', 'subrubro', 'Frutos Secos', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('FRUTOS SECOS', 'subrubro', 'Frutos secos', 14, 'min', 10, 'kg', 'articulo', false, null, true, null),
  ('FRUTOS SECOS', 'subrubro', 'Frutos Secos', 14, 'min', 10, 'kg', 'articulo', false, null, true, null),
  ('MANI TOSTADO SALADO', 'articulo', '653', 12, 'libre', null, null, null, false, null, true, null),
  ('MANI TOSTADO SALADO', 'articulo', '10672', 12, 'libre', null, null, null, false, null, true, null),
  ('MANI TOSTADO SALADO', 'articulo', '653', 13, 'min', 20, 'kg', 'articulo', false, null, true, null),
  ('MANI TOSTADO SALADO', 'articulo', '10672', 13, 'min', 20, 'kg', 'articulo', false, null, true, null),
  ('MANI TOSTADO SALADO', 'articulo', '653', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('MANI TOSTADO SALADO', 'articulo', '10672', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('MANI TOSTADO SIN SAL', 'articulo', '10640', 12, 'libre', null, null, null, false, null, false, '⚠️ SIN CONFIRMAR: en IM no hay ningún artículo que diga "sin sal". Se asume que son MANI TOSTADO KING x KG y x 10 KG. Confirmar con Mati.'),
  ('MANI TOSTADO SIN SAL', 'articulo', '10670', 12, 'libre', null, null, null, false, null, false, '⚠️ SIN CONFIRMAR: en IM no hay ningún artículo que diga "sin sal". Se asume que son MANI TOSTADO KING x KG y x 10 KG. Confirmar con Mati.'),
  ('MANI TOSTADO SIN SAL', 'articulo', '10640', 13, 'min', 10, 'kg', 'articulo', false, null, false, '⚠️ SIN CONFIRMAR: en IM no hay ningún artículo que diga "sin sal". Se asume que son MANI TOSTADO KING x KG y x 10 KG. Confirmar con Mati.'),
  ('MANI TOSTADO SIN SAL', 'articulo', '10670', 13, 'min', 10, 'kg', 'articulo', false, null, false, '⚠️ SIN CONFIRMAR: en IM no hay ningún artículo que diga "sin sal". Se asume que son MANI TOSTADO KING x KG y x 10 KG. Confirmar con Mati.'),
  ('MANI TOSTADO SIN SAL', 'articulo', '10640', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, false, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('MANI TOSTADO SIN SAL', 'articulo', '10670', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, false, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('PRALINE', 'articulo', '656', 12, 'libre', null, null, null, false, null, true, null),
  ('PRALINE', 'articulo', '2009', 12, 'libre', null, null, null, false, null, true, null),
  ('PRALINE', 'articulo', '10671', 12, 'libre', null, null, null, false, null, true, null),
  ('PRALINE', 'articulo', '10680', 12, 'libre', null, null, null, false, null, true, null),
  ('PRALINE', 'articulo', '656', 13, 'min', 10, 'kg', 'articulo', false, null, true, null),
  ('PRALINE', 'articulo', '2009', 13, 'min', 10, 'kg', 'articulo', false, null, true, null),
  ('PRALINE', 'articulo', '10671', 13, 'min', 10, 'kg', 'articulo', false, null, true, null),
  ('PRALINE', 'articulo', '10680', 13, 'min', 10, 'kg', 'articulo', false, null, true, null),
  ('PRALINE', 'articulo', '656', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('PRALINE', 'articulo', '2009', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('PRALINE', 'articulo', '10671', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('PRALINE', 'articulo', '10680', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('PASTAS MANI', 'subrubro', 'Pastas de Mani', 12, 'libre', null, null, null, false, null, true, null),
  ('PASTAS MANI', 'subrubro', 'Pastas de Mani', 13, 'min', 10, 'bulto', 'linea', false, null, true, null),
  ('PASTAS MANI', 'subrubro', 'Pastas de Mani', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('ARROZ', 'articulo', '700', 12, 'libre', null, null, null, false, null, true, null),
  ('ARROZ', 'articulo', '700', 13, 'min', 10, 'bulto', 'linea', false, null, true, null),
  ('ARROZ', 'articulo', '700', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('LEGUMBRES', 'subrubro', 'Legumbres', 12, 'libre', null, null, null, false, null, true, 'Polenta y harina de maíz tienen regla propia por código.'),
  ('LEGUMBRES', 'subrubro', 'Legumbres', 13, 'min', 10, 'kg', 'articulo', false, null, true, 'Polenta y harina de maíz tienen regla propia por código.'),
  ('LEGUMBRES', 'subrubro', 'Legumbres', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('LEGUMBRES', 'subrubro', 'Legumbres', 14, 'bulto_cerrado', null, null, null, true, null, true, 'Polenta y harina de maíz tienen regla propia por código. La bolsa habilita esta lista; el 10% extra es decisión del vendedor, no un derecho del cliente.'),
  ('RATISADA ULTRA JERINGA', 'articulo', '1959', 12, 'libre', null, null, null, false, null, false, '⚠️ SIN CONFIRMAR: en IM están RATISADA LIQ. x 1 LT y x 500 CC, no una "ultra jeringa". Las jeringas que hay son CUCAXAN y GERMANI GEL.'),
  ('RATISADA ULTRA JERINGA', 'articulo', '1960', 12, 'libre', null, null, null, false, null, false, '⚠️ SIN CONFIRMAR: en IM están RATISADA LIQ. x 1 LT y x 500 CC, no una "ultra jeringa". Las jeringas que hay son CUCAXAN y GERMANI GEL.'),
  ('RATISADA ULTRA JERINGA', 'articulo', '1959', 13, 'min', 11, 'bulto', 'linea', false, '10+1', false, '⚠️ SIN CONFIRMAR: en IM están RATISADA LIQ. x 1 LT y x 500 CC, no una "ultra jeringa". Las jeringas que hay son CUCAXAN y GERMANI GEL.'),
  ('RATISADA ULTRA JERINGA', 'articulo', '1960', 13, 'min', 11, 'bulto', 'linea', false, '10+1', false, '⚠️ SIN CONFIRMAR: en IM están RATISADA LIQ. x 1 LT y x 500 CC, no una "ultra jeringa". Las jeringas que hay son CUCAXAN y GERMANI GEL.'),
  ('RATISADA ULTRA JERINGA', 'articulo', '1959', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, false, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('RATISADA ULTRA JERINGA', 'articulo', '1960', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, false, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('RATISADA ULTRA JERINGA', 'articulo', '1959', 14, 'libre', null, null, null, false, null, false, '⚠️ SIN CONFIRMAR: en IM están RATISADA LIQ. x 1 LT y x 500 CC, no una "ultra jeringa". Las jeringas que hay son CUCAXAN y GERMANI GEL. La planilla dice "20% DCTO": ese descuento YA ESTÁ en el precio de esta lista en IM, así que el vendedor elige la lista y no carga un descuento aparte.'),
  ('RATISADA ULTRA JERINGA', 'articulo', '1960', 14, 'libre', null, null, null, false, null, false, '⚠️ SIN CONFIRMAR: en IM están RATISADA LIQ. x 1 LT y x 500 CC, no una "ultra jeringa". Las jeringas que hay son CUCAXAN y GERMANI GEL. La planilla dice "20% DCTO": ese descuento YA ESTÁ en el precio de esta lista en IM, así que el vendedor elige la lista y no carga un descuento aparte.'),
  ('COLLAR ANTIPULGA', 'articulo', '921', 12, 'libre', null, null, null, false, null, true, null),
  ('COLLAR ANTIPULGA', 'articulo', '922', 12, 'libre', null, null, null, false, null, true, null),
  ('COLLAR ANTIPULGA', 'articulo', '923', 12, 'libre', null, null, null, false, null, true, null),
  ('COLLAR ANTIPULGA', 'articulo', '924', 12, 'libre', null, null, null, false, null, true, null),
  ('COLLAR ANTIPULGA', 'articulo', '921', 13, 'min', 11, 'bulto', 'linea', false, '10+1', true, null),
  ('COLLAR ANTIPULGA', 'articulo', '922', 13, 'min', 11, 'bulto', 'linea', false, '10+1', true, null),
  ('COLLAR ANTIPULGA', 'articulo', '923', 13, 'min', 11, 'bulto', 'linea', false, '10+1', true, null),
  ('COLLAR ANTIPULGA', 'articulo', '924', 13, 'min', 11, 'bulto', 'linea', false, '10+1', true, null),
  ('COLLAR ANTIPULGA', 'articulo', '921', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('COLLAR ANTIPULGA', 'articulo', '922', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('COLLAR ANTIPULGA', 'articulo', '923', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('COLLAR ANTIPULGA', 'articulo', '924', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('COLLAR ANTIPULGA', 'articulo', '921', 14, 'libre', null, null, null, false, null, true, 'La planilla dice "20% DCTO": ese descuento YA ESTÁ en el precio de esta lista en IM, así que el vendedor elige la lista y no carga un descuento aparte.'),
  ('COLLAR ANTIPULGA', 'articulo', '922', 14, 'libre', null, null, null, false, null, true, 'La planilla dice "20% DCTO": ese descuento YA ESTÁ en el precio de esta lista en IM, así que el vendedor elige la lista y no carga un descuento aparte.'),
  ('COLLAR ANTIPULGA', 'articulo', '923', 14, 'libre', null, null, null, false, null, true, 'La planilla dice "20% DCTO": ese descuento YA ESTÁ en el precio de esta lista en IM, así que el vendedor elige la lista y no carga un descuento aparte.'),
  ('COLLAR ANTIPULGA', 'articulo', '924', 14, 'libre', null, null, null, false, null, true, 'La planilla dice "20% DCTO": ese descuento YA ESTÁ en el precio de esta lista en IM, así que el vendedor elige la lista y no carga un descuento aparte.'),
  ('SHULLET', 'articulo', '766', 12, 'libre', null, null, null, false, null, true, null),
  ('SHULLET', 'articulo', '767', 12, 'libre', null, null, null, false, null, true, null),
  ('SHULLET', 'articulo', '768', 12, 'libre', null, null, null, false, null, true, null),
  ('SHULLET', 'articulo', '769', 12, 'libre', null, null, null, false, null, true, null),
  ('SHULLET', 'articulo', '766', 13, 'min', 11, 'bulto', 'linea', false, '10+1', true, null),
  ('SHULLET', 'articulo', '767', 13, 'min', 11, 'bulto', 'linea', false, '10+1', true, null),
  ('SHULLET', 'articulo', '768', 13, 'min', 11, 'bulto', 'linea', false, '10+1', true, null),
  ('SHULLET', 'articulo', '769', 13, 'min', 11, 'bulto', 'linea', false, '10+1', true, null),
  ('SHULLET', 'articulo', '766', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('SHULLET', 'articulo', '767', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('SHULLET', 'articulo', '768', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('SHULLET', 'articulo', '769', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('SHULLET', 'articulo', '766', 14, 'libre', null, null, null, false, null, true, 'La planilla dice "20% DCTO": ese descuento YA ESTÁ en el precio de esta lista en IM, así que el vendedor elige la lista y no carga un descuento aparte.'),
  ('SHULLET', 'articulo', '767', 14, 'libre', null, null, null, false, null, true, 'La planilla dice "20% DCTO": ese descuento YA ESTÁ en el precio de esta lista en IM, así que el vendedor elige la lista y no carga un descuento aparte.'),
  ('SHULLET', 'articulo', '768', 14, 'libre', null, null, null, false, null, true, 'La planilla dice "20% DCTO": ese descuento YA ESTÁ en el precio de esta lista en IM, así que el vendedor elige la lista y no carga un descuento aparte.'),
  ('SHULLET', 'articulo', '769', 14, 'libre', null, null, null, false, null, true, 'La planilla dice "20% DCTO": ese descuento YA ESTÁ en el precio de esta lista en IM, así que el vendedor elige la lista y no carga un descuento aparte.'),
  ('SHAMPOO', 'articulo', '987', 12, 'libre', null, null, null, false, null, true, 'Sólo los de mascotas. Los shampoos de Limpieza (12642, 12645-12648) no entran.'),
  ('SHAMPOO', 'articulo', '988', 12, 'libre', null, null, null, false, null, true, 'Sólo los de mascotas. Los shampoos de Limpieza (12642, 12645-12648) no entran.'),
  ('SHAMPOO', 'articulo', '989', 12, 'libre', null, null, null, false, null, true, 'Sólo los de mascotas. Los shampoos de Limpieza (12642, 12645-12648) no entran.'),
  ('SHAMPOO', 'articulo', '990', 12, 'libre', null, null, null, false, null, true, 'Sólo los de mascotas. Los shampoos de Limpieza (12642, 12645-12648) no entran.'),
  ('SHAMPOO', 'articulo', '991', 12, 'libre', null, null, null, false, null, true, 'Sólo los de mascotas. Los shampoos de Limpieza (12642, 12645-12648) no entran.'),
  ('SHAMPOO', 'articulo', '992', 12, 'libre', null, null, null, false, null, true, 'Sólo los de mascotas. Los shampoos de Limpieza (12642, 12645-12648) no entran.'),
  ('SHAMPOO', 'articulo', '1987', 12, 'libre', null, null, null, false, null, true, 'Sólo los de mascotas. Los shampoos de Limpieza (12642, 12645-12648) no entran.'),
  ('SHAMPOO', 'articulo', '987', 13, 'min', 11, 'bulto', 'linea', false, '10+1', true, 'Sólo los de mascotas. Los shampoos de Limpieza (12642, 12645-12648) no entran.'),
  ('SHAMPOO', 'articulo', '988', 13, 'min', 11, 'bulto', 'linea', false, '10+1', true, 'Sólo los de mascotas. Los shampoos de Limpieza (12642, 12645-12648) no entran.'),
  ('SHAMPOO', 'articulo', '989', 13, 'min', 11, 'bulto', 'linea', false, '10+1', true, 'Sólo los de mascotas. Los shampoos de Limpieza (12642, 12645-12648) no entran.'),
  ('SHAMPOO', 'articulo', '990', 13, 'min', 11, 'bulto', 'linea', false, '10+1', true, 'Sólo los de mascotas. Los shampoos de Limpieza (12642, 12645-12648) no entran.'),
  ('SHAMPOO', 'articulo', '991', 13, 'min', 11, 'bulto', 'linea', false, '10+1', true, 'Sólo los de mascotas. Los shampoos de Limpieza (12642, 12645-12648) no entran.'),
  ('SHAMPOO', 'articulo', '992', 13, 'min', 11, 'bulto', 'linea', false, '10+1', true, 'Sólo los de mascotas. Los shampoos de Limpieza (12642, 12645-12648) no entran.'),
  ('SHAMPOO', 'articulo', '1987', 13, 'min', 11, 'bulto', 'linea', false, '10+1', true, 'Sólo los de mascotas. Los shampoos de Limpieza (12642, 12645-12648) no entran.'),
  ('SHAMPOO', 'articulo', '987', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('SHAMPOO', 'articulo', '988', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('SHAMPOO', 'articulo', '989', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('SHAMPOO', 'articulo', '990', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('SHAMPOO', 'articulo', '991', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('SHAMPOO', 'articulo', '992', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('SHAMPOO', 'articulo', '1987', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('SHAMPOO', 'articulo', '987', 14, 'libre', null, null, null, false, null, true, 'Sólo los de mascotas. Los shampoos de Limpieza (12642, 12645-12648) no entran. La planilla dice "20% DCTO": ese descuento YA ESTÁ en el precio de esta lista en IM, así que el vendedor elige la lista y no carga un descuento aparte.'),
  ('SHAMPOO', 'articulo', '988', 14, 'libre', null, null, null, false, null, true, 'Sólo los de mascotas. Los shampoos de Limpieza (12642, 12645-12648) no entran. La planilla dice "20% DCTO": ese descuento YA ESTÁ en el precio de esta lista en IM, así que el vendedor elige la lista y no carga un descuento aparte.'),
  ('SHAMPOO', 'articulo', '989', 14, 'libre', null, null, null, false, null, true, 'Sólo los de mascotas. Los shampoos de Limpieza (12642, 12645-12648) no entran. La planilla dice "20% DCTO": ese descuento YA ESTÁ en el precio de esta lista en IM, así que el vendedor elige la lista y no carga un descuento aparte.'),
  ('SHAMPOO', 'articulo', '990', 14, 'libre', null, null, null, false, null, true, 'Sólo los de mascotas. Los shampoos de Limpieza (12642, 12645-12648) no entran. La planilla dice "20% DCTO": ese descuento YA ESTÁ en el precio de esta lista en IM, así que el vendedor elige la lista y no carga un descuento aparte.'),
  ('SHAMPOO', 'articulo', '991', 14, 'libre', null, null, null, false, null, true, 'Sólo los de mascotas. Los shampoos de Limpieza (12642, 12645-12648) no entran. La planilla dice "20% DCTO": ese descuento YA ESTÁ en el precio de esta lista en IM, así que el vendedor elige la lista y no carga un descuento aparte.'),
  ('SHAMPOO', 'articulo', '992', 14, 'libre', null, null, null, false, null, true, 'Sólo los de mascotas. Los shampoos de Limpieza (12642, 12645-12648) no entran. La planilla dice "20% DCTO": ese descuento YA ESTÁ en el precio de esta lista en IM, así que el vendedor elige la lista y no carga un descuento aparte.'),
  ('SHAMPOO', 'articulo', '1987', 14, 'libre', null, null, null, false, null, true, 'Sólo los de mascotas. Los shampoos de Limpieza (12642, 12645-12648) no entran. La planilla dice "20% DCTO": ese descuento YA ESTÁ en el precio de esta lista en IM, así que el vendedor elige la lista y no carga un descuento aparte.'),
  ('TALQUERA PULGUICIDA', 'articulo', '993', 12, 'libre', null, null, null, false, null, true, 'Sólo el pulguicida de mascotas; las talqueras de hormigas son otra cosa.'),
  ('TALQUERA PULGUICIDA', 'articulo', '993', 13, 'min', 11, 'bulto', 'linea', false, '10+1', true, 'Sólo el pulguicida de mascotas; las talqueras de hormigas son otra cosa.'),
  ('TALQUERA PULGUICIDA', 'articulo', '993', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('PIPETAS', 'articulo', '962', 12, 'libre', null, null, null, false, null, true, null),
  ('PIPETAS', 'articulo', '963', 12, 'libre', null, null, null, false, null, true, null),
  ('PIPETAS', 'articulo', '964', 12, 'libre', null, null, null, false, null, true, null),
  ('PIPETAS', 'articulo', '965', 12, 'libre', null, null, null, false, null, true, null),
  ('PIPETAS', 'articulo', '966', 12, 'libre', null, null, null, false, null, true, null),
  ('PIPETAS', 'articulo', '10961', 12, 'libre', null, null, null, false, null, true, null),
  ('PIPETAS', 'articulo', '962', 13, 'min', 11, 'bulto', 'linea', false, '10+1', true, null),
  ('PIPETAS', 'articulo', '963', 13, 'min', 11, 'bulto', 'linea', false, '10+1', true, null),
  ('PIPETAS', 'articulo', '964', 13, 'min', 11, 'bulto', 'linea', false, '10+1', true, null),
  ('PIPETAS', 'articulo', '965', 13, 'min', 11, 'bulto', 'linea', false, '10+1', true, null),
  ('PIPETAS', 'articulo', '966', 13, 'min', 11, 'bulto', 'linea', false, '10+1', true, null),
  ('PIPETAS', 'articulo', '10961', 13, 'min', 11, 'bulto', 'linea', false, '10+1', true, null),
  ('PIPETAS', 'articulo', '962', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('PIPETAS', 'articulo', '963', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('PIPETAS', 'articulo', '964', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('PIPETAS', 'articulo', '965', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('PIPETAS', 'articulo', '966', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('PIPETAS', 'articulo', '10961', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('PIPETAS', 'articulo', '962', 14, 'min', 20, 'bulto', 'linea', false, null, true, null),
  ('PIPETAS', 'articulo', '963', 14, 'min', 20, 'bulto', 'linea', false, null, true, null),
  ('PIPETAS', 'articulo', '964', 14, 'min', 20, 'bulto', 'linea', false, null, true, null),
  ('PIPETAS', 'articulo', '965', 14, 'min', 20, 'bulto', 'linea', false, null, true, null),
  ('PIPETAS', 'articulo', '966', 14, 'min', 20, 'bulto', 'linea', false, null, true, null),
  ('PIPETAS', 'articulo', '10961', 14, 'min', 20, 'bulto', 'linea', false, null, true, null),
  ('PIEDRAS SANITARIAS', 'articulo', '961', 12, 'libre', null, null, null, false, null, true, 'El subrubro mezcla muchas cosas: la regla va por código de artículo.'),
  ('PIEDRAS SANITARIAS', 'articulo', '995', 12, 'libre', null, null, null, false, null, true, 'El subrubro mezcla muchas cosas: la regla va por código de artículo.'),
  ('PIEDRAS SANITARIAS', 'articulo', '1009', 12, 'libre', null, null, null, false, null, true, 'El subrubro mezcla muchas cosas: la regla va por código de artículo.'),
  ('PIEDRAS SANITARIAS', 'articulo', '961', 13, 'min', 6, 'bulto', 'linea', false, '5+1', true, 'El subrubro mezcla muchas cosas: la regla va por código de artículo.'),
  ('PIEDRAS SANITARIAS', 'articulo', '995', 13, 'min', 6, 'bulto', 'linea', false, '5+1', true, 'El subrubro mezcla muchas cosas: la regla va por código de artículo.'),
  ('PIEDRAS SANITARIAS', 'articulo', '1009', 13, 'min', 6, 'bulto', 'linea', false, '5+1', true, 'El subrubro mezcla muchas cosas: la regla va por código de artículo.'),
  ('PIEDRAS SANITARIAS', 'articulo', '961', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('PIEDRAS SANITARIAS', 'articulo', '995', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('PIEDRAS SANITARIAS', 'articulo', '1009', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '10 bultos surtidos en el pedido habilitan la Lista 2 (sigue vigente al 08/09/2026). Es otro camino, en paralelo a la condición propia de la línea.'),
  ('PIEDRAS SANITARIAS', 'articulo', '961', 14, 'min', 50, 'bulto', 'linea', false, null, true, 'El subrubro mezcla muchas cosas: la regla va por código de artículo.'),
  ('PIEDRAS SANITARIAS', 'articulo', '995', 14, 'min', 50, 'bulto', 'linea', false, null, true, 'El subrubro mezcla muchas cosas: la regla va por código de artículo.'),
  ('PIEDRAS SANITARIAS', 'articulo', '1009', 14, 'min', 50, 'bulto', 'linea', false, null, true, 'El subrubro mezcla muchas cosas: la regla va por código de artículo.'),
  ('PIEDRAS SANITARIAS', 'articulo', '961', 15, 'min', 60, 'bulto', 'articulo', false, null, true, 'Un pallet son 60 bolsas de este artículo (Mati, 08/09/2026).'),
  ('PIEDRAS SANITARIAS', 'articulo', '995', 15, 'min', 120, 'bulto', 'articulo', false, null, true, 'Un pallet son 120 bolsas de este artículo (Mati, 08/09/2026).'),
  ('PIEDRAS SANITARIAS', 'articulo', '1009', 15, 'min', 70, 'bulto', 'articulo', false, null, true, 'Un pallet son 70 bolsas de este artículo (Mati, 08/09/2026).'),
  ('LINEA KEN-L', 'subrubro', 'Ken-L', 12, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('LINEA KEN-L', 'subrubro', 'Ken-L', 13, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('PELLET ALFA', 'articulo', '10456', 12, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('PELLET ALFA', 'articulo', '10456', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('GALLETAS PITUSAS', 'subrubro', 'Galletas', 12, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('PALITO SALADO', 'articulo', '655', 12, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('ROCKLETS', 'articulo', '13128', 12, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('ROCKLETS', 'articulo', '13128', 13, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('FRACCIONADOS KING Y NUTRIFOOD', 'subrubro', 'Fraccionado', 12, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('POLENTA Y HARINA DE MAIZ', 'articulo', '722', 12, 'max', 10, 'kg', 'articulo', false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('POLENTA Y HARINA DE MAIZ', 'articulo', '722', 13, 'min', 10, 'kg', 'articulo', false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('POLENTA Y HARINA DE MAIZ', 'articulo', '716', 12, 'max', 10, 'kg', 'articulo', false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('POLENTA Y HARINA DE MAIZ', 'articulo', '716', 13, 'min', 10, 'kg', 'articulo', false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Perros y Gatos', 12, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Perros y Gatos', 13, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Perros y Gatos', 14, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Perros y Gatos', 15, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Plantas', 12, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Plantas', 13, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Plantas', 14, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Plantas', 15, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Aves', 12, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Aves', 13, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Aves', 14, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Aves', 15, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Peces', 12, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Peces', 13, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Peces', 14, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Peces', 15, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Hamsters', 12, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Hamsters', 13, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Hamsters', 14, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('LINEA KEN-L', 'subrubro', 'Ken-L', 14, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('VICIA', 'articulo', '474', 12, 'max', 20, 'kg', 'articulo', false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('VICIA', 'articulo', '474', 13, 'min', 20, 'kg', 'articulo', false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('VICIA', 'articulo', '474', 14, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('VITAMINA', 'articulo', '475', 12, 'max', 20, 'kg', 'articulo', false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('VITAMINA', 'articulo', '475', 13, 'min', 20, 'kg', 'articulo', false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('VITAMINA', 'articulo', '475', 14, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('MAIZ CUARENTIN', 'articulo', '461', 12, 'max', 20, 'kg', 'articulo', false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('MAIZ CUARENTIN', 'articulo', '461', 13, 'min', 20, 'kg', 'articulo', false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Hamsters', 15, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Animales Granja', 12, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Animales Granja', 13, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Animales Granja', 14, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Accesorios Animales Granja', 15, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Venenos Insectos', 12, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Venenos Insectos', 13, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Venenos Insectos', 14, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Venenos Insectos', 15, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Venenos Ratas', 12, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Venenos Ratas', 13, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Venenos Ratas', 14, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Venenos Ratas', 15, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Venenos Hormigas', 12, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Venenos Hormigas', 13, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Venenos Hormigas', 14, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Venenos Hormigas', 15, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Venenos Moscas y Cucarachas', 12, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Venenos Moscas y Cucarachas', 13, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Venenos Moscas y Cucarachas', 14, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('ACCESORIOS Y VENENOS', 'subrubro', 'Venenos Moscas y Cucarachas', 15, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('EXACT CRIADORES', 'subrubro', 'Exact Criadores', 12, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('EXACT CRIADORES', 'subrubro', 'Exact Criadores', 13, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('EXACT CRIADORES', 'subrubro', 'Exact Criadores', 14, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('SNACKS TIERNITOS', 'articulo', '190', 12, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('SNACKS TIERNITOS', 'articulo', '191', 12, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('PELLET SANITARIO', 'articulo', '1010', 12, 'libre', null, null, null, false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('PELLET SANITARIO', 'articulo', '1010', 13, 'promo_general', 10, 'bulto', 'pedido', false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.'),
  ('PELLET SANITARIO', 'articulo', '1010', 14, 'min', 5, 'bulto', 'articulo', false, null, true, '⚠️ HEREDADA: no figura en la planilla del 08/09/2026. Se conserva para no dejar la línea sin control; confirmar con Mati si corresponde mantenerla.');
